### ISSUE TITLE
Вид списка - клик на квадартик выбора открывает папку

### ISSUE THREAD

**Issue by b2z** [Quantum-Manager/tracker#1]
Когда включен вид списка, то клик на квадратик выбора папки не выберает её, а делает переход в эту папку. Это не даёт возможность выбрать папку / несколько папок.

**Comment by dmitriitux** [comment]
поправил
https://github.com/Quantum-Manager/quantummanager/commit/37fee96409b85231134f0fdd66d4041e4aa5eb0c
