### ISSUE TITLE
Pasting Text creates image

### ISSUE THREAD

**Issue by coolcat-creations** [Quantum-Manager/tracker#102]
### Steps to reproduce the issue
1) Download this Powerpoint File:

[test.pptx](https://github.com/Quantum-Manager/tracker/files/8564129/test.pptx)

2) Place your textcursor into the Test... Word (the one with the arrow in front)
select all, copy

3) In your Joomla 3.10.8 installation click on the code editor and paste what you just copied from that file:
<img width="76" alt="grafik" src="https://user-images.githubusercontent.com/828371/165321740-7294f0d0-fd52-4c34-a198-f1616565591d.png">

<img width="656" alt="grafik" src="https://user-images.githubusercontent.com/828371/165321845-dcb359c0-8b91-4428-8d0f-c180ae5ff795.png">

4) Click ok, do not even save this and change to the images and Links tab.

One of those two scenarios appears:

<img width="725" alt="grafik" src="https://user-images.githubusercontent.com/828371/165322090-c434bc1d-16ec-4b0f-98fd-b4a2c723650d.png">

<img width="611" alt="grafik" src="https://user-images.githubusercontent.com/828371/165322255-5a282f18-0fa2-4ea0-bfc8-2b0f8ab14e9f.png">

### Expected result
No image should be created when pasting something into code editor...
Its just TinyMCE and Quantum, on a normal installation all works as expected  - It's very weird...

**Comment by dmitriitux** [comment]
yes, I know about this problem, I fixed it in the dev package, you can install it, it is inserted from the buffer there only when the quantum window is active.  I am also engaged in the adaptation of quantum for joomla 4. That is, this package is already installed on joomla 4, you can try it on your test site.  Everything works there except modal windows and the interception plugin.

Dev package:
https://hika.su/builds/free/dev_pkg_quantummanager.zip

**Comment by coolcat-creations** [comment]
Thank you, sounds awesome!!!

**Comment by dmitriitux** [comment]
@coolcat-creations 
https://github.com/Quantum-Manager/start/blob/master/ru.changelog.md
I keep the current changelog here in Russian, you can look through the translator (there I keep what is in the dev version)

**Comment by coolcat-creations** [comment]
thank you
