### ISSUE TITLE
Does not work with PHP 8.1

### ISSUE THREAD

**Issue by MikeTaifun** [Quantum-Manager/tracker#105]
Can not create folder or file list in div class=field-list-files on website with PHP 8.1. When switching back to 7.4.30 it works perfectly again without any further changes.
System Information:
Quantum Manager 1.8.0.
Joomla 3.10.9.
PHP FPM 8.1.7.
Server Linux Apache
Browser Chrome 102.0

**Comment by dmitriitux** [comment]
we will make a release the other day, we drove on php 8.1.4, everything works

**Comment by dmitriitux** [comment]
check on new release

**Comment by MikeTaifun** [comment]
Thank you, i'd like to confirm, v2.0 works perfectly under PHP 8.1.
