### ISSUE TITLE
Error Message "Unable to load the structure of a folder"

### ISSUE THREAD

**Issue by coolcat-creations** [Quantum-Manager/tracker#108]
Happens In Joomla 4.1.4 when trying to change the intro image in an article (com_content)

![grafik](https://user-images.githubusercontent.com/828371/174746449-3dc3aa10-b2de-4b59-8ca1-1d209e738e77.png)

**Comment by dmitriitux** [comment]
@coolcat-creations 
can you see what is in the response from the server in the xhr request?

**Comment by dmitriitux** [comment]
@coolcat-creations if it's on a server on Windows, then I broke something there with paths, I haven't fixed it yet =)

**Comment by SLAVAWEBru** [comment]
I have the same problem on the Open Server. How can I fix this

**Comment by dmitriitux** [comment]
> I have the same problem on the Open Server. How can I fix this

I made mistakes somewhere in compiling paths, I just write everywhere under unix systems and forget about windows features. You won’t fix it yourself, I need to go through the code and fix the paths, I’ll take a look, I think I’ll fix it in the next update

**Comment by LadySolveig** [comment]
@SLAVAWEBru I had the same error and forked the project to fix this. If you have Joomla 3.10 and PHP 8 then this could be a fast solution for you.
https://github.com/LadySolveig/quantummanager
@coolcat-creations I've not tested my solution with joomla 4 yet.

@dmitriitux Thank you very much for this great media manager !!! 

Update @coolcat-creations 
I have installed on Joomla4 and my fix could propably help you also

![Screenshot 2022-07-06 153603](https://user-images.githubusercontent.com/64533137/177563243-f27a9b6a-2983-451b-8cda-8febe56eee69.png)

![Screenshot 2022-07-06 153707](https://user-images.githubusercontent.com/64533137/177563394-4e689ac9-1f84-4364-83bb-3cb44974663b.png)

**Comment by LadySolveig** [comment]
@dmitriitux @coolcat-creations @SLAVAWEBru
I found another Bug in /libraries/lib_fields/fields/quantumuploadimage/media/js/quantummodal.js

The path could not be resolved correctly for scope sessionroot because of the missing session variable with different sessions in Frontend and Backend. This fixes the false resolveing of the path.

If you want to add this fix manually you schould also change the line in 
/media/lib_fields/quantumuploadimage/js/quantummodal.js

![image](https://user-images.githubusercontent.com/64533137/178096094-52b8dfc3-ca55-4a49-a0a2-08bc7b1c344a.png)

![image](https://user-images.githubusercontent.com/64533137/178096218-8c3279df-de6e-4916-bb77-e0859110086e.png)

**Comment by dmitriitux** [comment]
@LadySolveig 
ok, I understand, I'll fix it. I will also review what you have made in the fork and transfer the meaning of the corrections to the quantum

**Comment by dmitriitux** [comment]
@LadySolveig I'll tell you a secret, I'm developing the whole quantum from scratch. I'm creating a graphical toolkit specifically for quantum =)

**Comment by dmitriitux** [comment]
@LadySolveig I put the full quantum extension there, you can create a graphic element and add new logic, for example, creating your own drivers for anything, for example, a driver for viewing Joomla materials, that is, any source.

**Comment by LadySolveig** [comment]
@dmitriitux Sounds very interesting!!! The Quantummanager is already a very cool and powerful tool. 
I made a PR for the jpel library. It fixes a Bug for the namespace registration in Joomla 4.x ;-)
[jpell PR - Bugfix for Joomla 4.x](https://github.com/Quantum-Manager/jpel/pull/1#issue-1308333918)

**Comment by dmitriitux** [comment]
@coolcat-creations @LadySolveig 
just got to quantum, realized the error and corrected it in the dev branch:

https://github.com/Quantum-Manager/quantummanager/commit/3c5b7d838668cccf5cf0364db8ca423c3f30908a
