### ISSUE TITLE
Не перехватывает Квантум на Joomla 4 что-то поля медиа-менеджера в материалах

### ISSUE THREAD

**Issue by bsakhanov** [Quantum-Manager/tracker#112]
**Опишите ошибку**
Не перехватывает Квантум на Joomla 4 что-то поля медиа-менеджера в материалах. Там даже опции в плагине соответствующем, переопределяющем, такой нет.

**Как воспроизвести**
Перейдите в управление плагинами. Найдите плагин "Система - Замена вызова медиа-менеджера (com_media) на Quantum Manager", там нет опций "Менеджер материалов", "Материал", также нет опций "Баннер" и ряда других, которые на Joomla 3 есть. Точнее, там — на джумле-тройке — можно спокойно выбрать из аякс-селекта выпадающего нужный компонент. А вот на J4 уже нет никакого выпадающего селекта из списка — просто уже как бы вбито в окошко выбора то, что ограничивается размером окошка и автоматом подтягивается и становится как бы автоматически "выбранным", а вот остальное из списка разного рода компонентов джумлы уже недоступным становится. 

**Ожидаемое поведение**
Хотелось бы, чтобы работало также четко как и на Joomla 3

**Скриншоты**
[вот скриншот][(url](https://cloud.mail.ru/public/D3E9/i7yyoF1XU))

**Информация о системе (пожалуйста, заполните следующую информацию):**
  - Версия Joomla: Joomla! 4.1.5 Stable
  - Версия Расширения [2.0.0]
  - Версия PHP: [7,4]
  - ОС Сервера: [Linux]
  - Браузер [яндекс-браузер]

**Comment by Sulpher** [comment]
попробуйте поставить последнюю версию 3.1.0. должно все работать.
<img width="898" alt="Снимок экрана 2024-07-02 в 10 54 51" src="https://github.com/Quantum-Manager/tracker/assets/3432048/9afbae81-f9d0-4fec-86ef-febf7688da99">
