### ISSUE TITLE
Произошла ошибка загрузки структуры папки после установки

### ISSUE THREAD

**Issue by IpVorMax** [Quantum-Manager/tracker#115]
Сразу после установки (отчет установки не содержал ошибок) при открытии главного окна компонента выводится ошибка "Произошла ошибка загрузки структуры папки." Joomla 4.1.5

**Comment by dmitriitux** [comment]
На опенсервере крутится?

**Comment by IpVorMax** [comment]
Да. Я уже понял, что на опенсервере не работает. Поставил на хостинг - полет нормальный. Спасибо за ответ и отличный компонент.

**Comment by gloriusglo** [comment]
Аналогичная ошибка. 
Joomla ‎4.2.3 и Joomla 3.10.11. Оба сайта на хостинге.
Куда рыть, подскажите.
