### ISSUE TITLE
Проблемы  с установкой из-за ограничений сервера. Вынести либу на Github

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#123]
Eugene Sivokon, [9 авг. 2022 г., 12:39:53]:
немецкий хостинг.

**Error
PKG_QUANTUMMANAGER_LIBFIELDS_INSTALLATION_ERROR**

```
Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /var/www/tmp/install_62f22b1f76e57/script.php on line 243

Warning: file_get_contents(https://hika.su/update/free/lib_fields.zip): failed to open stream: no suitable wrapper could be found in /var/www/tmp/install_62f22b1f76e57/script.php on line 243
```

а что будет, если так и оставить? глюки в квантум? многие пожмут плечами и оставят как есть.

не совсем понятно, что значит wrapper is disabled in the server configuration
т.е. дело в домене hika.su или то же самое будет и с Github?

**Comment by dmitriitux** [comment]
да, с гитхабом будет тоже самое, то есть они на шареде порезали конфиг пхп на внешний мир

**Comment by dmitriitux** [comment]
всю подсеть РФ только по слухам соседи наши заблокировали

**Comment by Sulpher** [comment]
> да, с гитхабом будет тоже самое, то есть они на шареде порезали конфиг пхп на внешний мир

ну это частный случай с хостером. в других случаях, как ты писал выше, могут заблочить подсеть РФ. в этом случае github выручит. туда нужно вынести либу.
