### ISSUE TITLE
Cannot declare class Lib_fieldsInstallerScript, because the name is already in use

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#145]
ставлю поверх версии 2.0.0 ту же самую версию (архив скачан 20.06.2022) и получаю это:

Ошибка
Internal Server Error

в логах: 
`[Wed Oct 19 00:23:38 2022] [proxy_fcgi:error] [pid 468101:tid] [client ] AH01071: Got error 'PHP message: PHP Fatal error:  Cannot declare class Lib_fieldsInstallerScript, because the name is already in use in /www/tmp/install_634f195aa5f84/script.php on line 9', referer: https://domain.ru/administrator/index.php?option=com_installer&view=install`

**Comment by dmitriitux** [comment]
поправил
