### ISSUE TITLE
no images visible in Quantum Manager

### ISSUE THREAD

**Issue by 12appletree** [Quantum-Manager/tracker#147]
I installed Quantum Manager (free version) and expect to see images (thumbnails).

Joomla version 3.10.11
db type mysql  - 10.5.16-MariaDB-cll-lve 
PHP 7.4.29
Apache/2 
litespeed

Browser: Firefox

On another site (other server) the QM is working OK, so it has something to do with the server settings, I think.
I like to test QM because of loading problems with the Joomla Media Manager. The site has many folders with 1.000's images in it.
![QM](https://user-images.githubusercontent.com/11877504/197792021-98ab1e99-7a0f-46e4-9551-ba08500093a6.jpg)

**Comment by dmitriitux** [comment]
there are no extensions that block the cache folder?

**Comment by Sulpher** [comment]
In addition to the previous comment: it might be Admin Tools which generates custom .htaccess that blocks folders and a user should add an exception for folder when generating .htaccess via Admin Tools.
