### ISSUE TITLE
Option to add Uppercase vs Lowercase filenames

### ISSUE THREAD

**Issue by raramuridesign** [Quantum-Manager/tracker#152]
**Describe the solution you'd like**
We would like to have the option to upload files without changing the case to lowercase.

Would you please consider this
M.

**Comment by dmitriitux** [comment]
ok, I'll split on two options in configuration. Now there is a setting to not touch the names at all don't convert anything

**Comment by raramuridesign** [comment]
@dmitriitux Thank you, has this been added already in a new release?

**Comment by dmitriitux** [comment]
@raramuridesign do not convert names at all yes, she has been for a long time

**Comment by raramuridesign** [comment]
@dmitriitux What is the setting for this, as I cannot find it, screenshot please.

**Comment by dmitriitux** [comment]
@raramuridesign Names in Unicode

**Comment by raramuridesign** [comment]
@dmitriitux Thanks. I found it, would be good to add some sort of note on this for the field as this was not obvious.
I am closing this for now.
