### ISSUE TITLE
Wrong path when Joomla! in a subfolder

### ISSUE THREAD

**Issue by jfquestiaux** [Quantum-Manager/tracker#153]
Hi,
I have a J!4 site installed in a subfolder (www.mydomain.com/fr) and Quantum manager does not work in that setting:
* It can't load the images because it's looking into https://www.mydomain.com/frindex.php?option=com_quantummanager&task=quantumtreecatalogs.getDirectories&path=root&root=root instead of https://www.mydomain.com/fr/index.php?...
* When you open the "Options", it goes to "www.mydomain.com/administrator" instead of "www.mydomain.com/fr/administrator"

Note that other extensions work fine in this setting.
Tested with J! 4.2.5 and Quantum Manager 2.0.0

**Comment by dmitriitux** [comment]
I corrected this error in the dev branch, I will try to update the quantum soon
