### ISSUE TITLE
Темный шаблон админки: элементы в темной гамме

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#155]
Шаблон админки bettum (темная тема)

некоторые элементы смотрятся плохо:
<img width="1185" alt="Снимок экрана 2022-11-12 в 18 45 00" src="https://user-images.githubusercontent.com/3432048/208265606-239461a7-7595-4d93-a6d9-ffb0c51eb47a.png">

**Comment by dmitriitux** [comment]
@Sulpher где можно скачать? посомтрю на каком основании он делает темную тему, переменные там джумловые переопределяются или как, я тогда на переменных сделаю

**Comment by Sulpher** [comment]
https://github.com/C-Lodder/joomla4-backend-template

**Comment by Sulpher** [comment]
еще темный шаблон админки:
https://github.com/nikosdion/DarkMagic
