### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by Nuyonuyonoina** [Quantum-Manager/tracker#157]
**Describe the bug**
Quantum Manager is infinitely loading.

**To Reproduce**
1. Go to 'Quantum Manager' or try to load an image in an article
2. Nothing is loading except the message "Loading"

**Expected behavior**
Media library loading.

**System Information (please complete the following information):**
- Joomla! 3.10.11 
 - Extensions version 2.0.0
 - PHP version: 8.1
 - Server OS: Linux
 - Browser: Chrome and Firefox

**Additional context**
PHP libraries: GD and ImageMagick
PHP memory limit: 256 Mb 
Don't know since when the bug exists. Maybe since version 2.0.0. One more detail, JIntervention library had been updated today, but really don't know if it's linked.

**Edit**
Tried on a new website in Joomla! ‎4.2.6, same issue.
It's a error 500 on .../administrator/index.php?option=com_quantummanager&task=quantumviewfiles.getFiles&path=root&scope=images&v=430901

**Comment by dmitriitux** [comment]
there is a bug in version 8.x, we will update the quantum soon

**Comment by Nuyonuyonoina** [comment]
Thanks a lot @dmitriitux Already updated. Everything fine.
