### ISSUE TITLE
Incomplete list of Extensions in quantummanagermedia Plugin

### ISSUE THREAD

**Issue by knowmatesSR** [Quantum-Manager/tracker#158]
**Describe the bug**
Incomplete list of Extensions for field "Where To Replace"

**To Reproduce**
1. Go to plugin settings of plg_quantummanagermedia 
2. Compare the list of this field with installed components

**Expected behavior**
All installed Component with it's views should show up

**Screenshots**

**System Information (please complete the following information):**
 - Extensions version 2.0.0
 - PHP version: all supoorted PHP Versions
 - Server OS: all supoorted OS
 - Browser: all browsers

**Additional context**
file: libraries/lib_fields/fields/listcomponents/listcomponents.php:82 
The lookup scheme is working for extensions in Joomla3 style but newer extensions and its views are not found because the views folder are located in a subfolder called "src". Component and view names should be converted to lowercase before using them as a select option value to get it working.

And it would be nice to use layout="joomla.form.field.list-fancy-select" for this field so users can search it.

**Comment by dmitriitux** [comment]
necessary corrections made

**Comment by artemkozirev** [comment]
Всем привет. Ошибка при установке квантум менеджера пишет про библиотеку 

![Image](https://github.com/user-attachments/assets/10867fd0-0e51-4461-831a-efecead8e2a4)
Destination folder not found
×
danger
Не удалось скачать библиотеку lib_fields с внешнего источника. Пожалуйста, установите её вручную: [скачать библиотеку](https://github.com/JPathRu/lib_fields/releases/latest/download/lib_fields.zip)
×
success
Установка пакета успешно завершена.
Пакет расширений для Quantum Manager

Скачиваю и не могу установить joomla 4.4.11
