### ISSUE TITLE
Последнее обновление сломало загрузку через Radical Multifield

### ISSUE THREAD

**Issue by d2boy** [Quantum-Manager/tracker#170]
После обновления при загрузке файлов в поле в консоли появляется ошибка 500 (путь обращения site.ru/administrator//administrator/plugin/multifield/…) , файлы загружаются в папку на диске, но не попадают в форму.
![Безымянный](https://user-images.githubusercontent.com/33113853/217172341-444ff068-3b4a-4921-8df5-d24a4120a26e.png)

**Comment by dmitriitux** [comment]
понял, на днях залью обновление, сегодня-завтра

**Comment by dmitriitux** [comment]
выпустил фикс, можете обновляться
