### ISSUE TITLE
en-GB translation - proofreading

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#172]
ORIGINAL:

Save EXIF meta tags
EXIF is a standard that specifies **the formats for images**, audio and media and adds meta-data recorded by digital cameras: authorship, coordinates of a place where the shoot was taken, date, license and etc. 

I suggest updating it to:

EXIF is a standard that specifies **format of images**, audio and media and adds meta-data recorded by digital cameras: authorship, coordinates of a place where the shoot was taken, date, license and etc.

**Comment by dmitriitux** [comment]
поправил
