### ISSUE TITLE
Frontend Error: JLIB_APPLICATION_ERROR_NOT_ACCESS

### ISSUE THREAD

**Issue by mediaventa** [Quantum-Manager/tracker#174]
**Error**
When I try to open the link to the Quantum Manager in the frontend I get the following error. I set the the rights for the link to _public_ to avoid an error caused by missing rights:

0 JLIB_APPLICATION_ERROR_NOT_ACCESS
/home/www/portal.historische-zeitschrift.com/components/com_quantummanager/controller.php:52

Call stack
--
# | Function | Location
1 | () | JROOT/components/com_quantummanager/controller.php:52
2 | QuantummanagerController::getInstance() | JROOT/components/com_quantummanager/quantummanager.php:16
3 | require_once() | JROOT/libraries/src/Component/ComponentHelper.php:402
4 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT/libraries/src/Component/ComponentHelper.php:377
5 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:194
6 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:233
7 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:225
8 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/index.php:49

**Software**
Quantum Manager 2.0.2 / Joomla 3.10.11 / PHP 8.0

**Link**
https://portal.historische-zeitschrift.com/quantum

**Comment by b2z** [comment]
Probably this will help #169

**Comment by mediaventa** [comment]
Yes, that's it. Sorry, I didn't see the configuration option in the general tab.

**Comment by b2z** [comment]
It's ok 🤗
