### ISSUE TITLE
Quantum manager don't show in custom fields

### ISSUE THREAD

**Issue by galamarco** [Quantum-Manager/tracker#176]
Hello,
I have a joomla website with custom field to have a gallery image in article.
![image](https://user-images.githubusercontent.com/5132398/225951489-66a84c23-cac0-4c35-ad82-1a754f42f9e1.png)

Custom fields in Joomal 4 to do it need to create a conteiner, type "subform"
![image](https://user-images.githubusercontent.com/5132398/225952258-17e6e39e-696f-4bf3-ace1-67bccb31d324.png)

and one ore more field type "media"
![image](https://user-images.githubusercontent.com/5132398/225953038-95a7ef1d-abf0-4676-9577-7156d9f01f1c.png)

In this custom fields quantum manager don't show.

**System Information:**
 - Extensions version: Quantum manager 2.0.2
 - PHP version: 8.0.27

**Comment by dmitriitux** [comment]
in the latest update, now there is field processing, only you need to transfer the media field redefinition plugin from quantum AFTER the system field plugin

**Comment by galamarco** [comment]
Sorry for the delay but I'm now discovering the answer to this problem.
I'm not sure I fully understand how to fix this problem.
I think I understand that that you suggest to sort the custom fields in a specific order. Did I get it right?
Could you explain to me better what operations need to be performed to correctly activate the quantum manager in custom fields?

I have these custom fields
![image](https://github.com/Quantum-Manager/tracker/assets/5132398/149ac8cb-0688-4e39-8543-2e0ec3619e4a)

but they are shown like this
![image](https://github.com/Quantum-Manager/tracker/assets/5132398/7af599d7-d98b-4e60-aceb-c9c912d5ac86)

Thanks a lot
Marco
