### ISSUE TITLE
Showing image title as image caption

### ISSUE THREAD

**Issue by pnkr** [Quantum-Manager/tracker#18]
**Is your feature request related to a problem? Please describe.**
There is no option for showing image titles when inserting an image inside an article.

**Describe the solution you'd like**
Having an option to show or not show the image title as caption when inserting an image in article content.

**Describe alternatives you've considered**
For now i just type a paragraph under the image.

**Comment by b2z** [comment]
Hello.

It is possible via embed templates. See the [corresponding documentation](https://norrnext.com/docs/joomla-extensions/quantum-manager/editor-button) about Editor Button.

**Comment by pnkr** [comment]
Didnt knew that!!! Wow! Incredible functionality.

**Comment by b2z** [comment]
You are welcome :+1:
