### ISSUE TITLE
Drop area in article edit - image intro - files goes to root / public_html

### ISSUE THREAD

**Issue by ghost** [Quantum-Manager/tracker#180]
As in title, when drop image file to drop area, the file is saved in public_html. Should save in image folder by default or folder set in settings. Multiple users put files in that way and public_html is so dirty now.

**Comment by dmitriitux** [comment]
Is this Quantum boot field behaving like this?

**Comment by dmitriitux** [comment]
corrected, we will publish the script for correcting the articles

**Comment by ghost** [comment]
Very nice, can You tell me where I can download update package and script for move images from public_html to image folder? After that time of open ticket now its very, very, messy on public_html.

**Comment by ghost** [comment]
> corrected, we will publish the script for correcting the articles

Is the script already published ?

**Comment by ghost** [comment]
Please ?
