### ISSUE TITLE
Cannot disable PEXELS and PIXABAY in Front-End

### ISSUE THREAD

**Issue by Maroon125** [Quantum-Manager/tracker#183]
**Describe the bug**
Although the documentation on https://docs.norrnext.com/quantum-manager/configuration/images states that 'Unsplash', 'Pexels' and 'Pixabay' can be disabled, only 'Unsplash' option is visible in Quantum-Manager's options. In the back-end, 'Pexels' and 'Pixabay' don't appear at all but in the front-end you cannot disable this.

**To Reproduce**
1. Go to 'components' on back-end
2. Click on 'Quantum Manager - Options - Images'
3. Disable only available for  'Unsplash'
4. Check back-end / check front-end

**Expected behavior**
According to documentation there should be options to disable/enable 'Pexels' and 'Pixabay', too but it's not and it is always enabled in front-end.

**Screenshots**
![image](https://github.com/Quantum-Manager/tracker/assets/143544353/f4c9873c-4a59-4319-8954-02e648173a11)

**System Information (please complete the following information):**
 - Extensions version 2.0.2
 - PHP version: 8.1.22
 - Server OS: Linux
 - Browser Chrome, Edge

**Additional context**

**Comment by Sulpher** [comment]
Hello,
Thanks for your question. It is not bug.
Integration with Pixabay and Pexels removed since version 2.0.0. 
See changelog: 
https://norrnext.com/support/changelogs/quantum-manager

The documentation needs an update.

**Comment by Sulpher** [comment]
Ah, I misunderstood you.  
Now I reproduced this issue and see these icons are available at the front-end while support of these services are removed. 
Thanks for reporting! We'll fix it later.

**Comment by Maroon125** [comment]
Thanks 

Am 2. September 2023 12:19:33 MESZ schrieb Eugene ***@***.***>:

**Comment by dmitriitux** [comment]
поправил
