### ISSUE TITLE
Testing on Joomla 5 and PHP 8.2

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#186]
Compatibility plugin enabled:

<img width="1198" alt="Снимок экрана 2023-09-19 в 09 56 51" src="https://github.com/Quantum-Manager/tracker/assets/3432048/9d4d689d-67bb-4151-8b1b-1bcfd154ef85">

`Deprecated: Creation of dynamic property JFormFieldQuantumconfigpath::$prefix is deprecated in //public_html//libraries/src/Form/FormField.php on line 594`

Joomla 5 beta1, quantum manager 2.0.4

**Comment by Sulpher** [comment]
`[19-Sep-2023 06:58:50 UTC] PHP Deprecated:  mb_strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in /home//public_html/administrator/components/com_quantummanager/fields/quantumconfigscopetitle.php on line 42`

**Comment by Sulpher** [comment]
**Compatibility plugin disabled:**
1. An error has occurred.
    0 Class "JObject" not found
<img width="1592" alt="Снимок экрана 2023-10-22 в 13 24 33" src="https://github.com/Quantum-Manager/tracker/assets/3432048/2bfa9854-0562-4702-bdd5-2c5f06d5d33d">

2.  Class "JPlugin" not found 
JROOT/plugins/quickicon/quantummanagericon/quantummanagericon.php:17

**Comment by Sulpher** [comment]
This solution can help:
https://github.com/mfleeson/joomla_com_upgrader

**Comment by Sulpher** [comment]
php 8.2:
пользователь сообщил:
"вылазят ошибки при выборе файла (например, выбираю фото для материала):"
`Deprecated: Creation of dynamic property JFormFieldQuantumCombine::$fields is deprecated in...`

**Comment by dmitriitux** [comment]
поправил все
