### ISSUE TITLE
Пропуск позиционирования картинки

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#19]
Выбираю left для позиционирования картинки:
![Screen Shot 2020-05-28 at 23 04 39](https://user-images.githubusercontent.com/3432048/83188254-1291b180-a138-11ea-9f96-826ff1310643.png)

Должно вставиться class="pull-left", но атрибут пропущен:
![Screen Shot 2020-05-28 at 23 04 50](https://user-images.githubusercontent.com/3432048/83188258-14f40b80-a138-11ea-8824-5c4deaf856bd.png)

**Comment by dmitriitux** [comment]
а зачем? я делал именно это: http://htmlbook.ru/html/img/align

**Comment by Sulpher** [comment]
ну это логика TinyMCE. 
можно сделать, как ты написал, но сейчас не вставляется атрибут в целом.

**Comment by dmitriitux** [comment]
@Sulpher классы же вставляются? проверил, они вставляются, если ввести в "класс css"

**Comment by dmitriitux** [comment]
@Sulpher позиционирование поправил
https://github.com/Quantum-Manager/quantummanagermedia/commit/35c61c513bf3ae830f3d482d4a9b0380b54cf2fa

**Comment by dmitriitux** [comment]
проверил, работает теперь все
