### ISSUE TITLE
Joomla 5. Warnings during the installation

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#190]
Joomla 5.0.0. Joomla 8.2. Quantum Manager 2.0.4
<img width="1061" alt="Снимок экрана 2023-10-22 в 13 18 46" src="https://github.com/Quantum-Manager/tracker/assets/3432048/6e4368c4-3751-4f1b-adfa-a14038880818">

1. не скачалась lib_fields почему-то. либо дело в сервере, либо либу обновить нужно.
2. Package for Quantum Manager
что это значит?
что за пакет установился ДЛЯ Quantum?
или это Quantum сам по себе? если да, то фраза нужна такая:
Quantum Manager package

**Comment by dmitriitux** [comment]
поправил на Quantum Manager package

**Comment by dmitriitux** [comment]
проблемы все пофиксил тут
