### ISSUE TITLE
Локализация плагина интеграции YT:  пропущенная константа

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#20]
![photo_2020-05-28_17-50-09](https://user-images.githubusercontent.com/3432048/83189099-5f29bc80-a139-11ea-9b2a-bbbaf6d84fb1.jpg)
удаление папки  в YT. когда спрашивает точно удалить папку или нет там константа языковая не сработала. 

[Forwarded]
Я вызвал через конструктор прошки, а удаление нажал по правому клику

надо загрузить языки.

**Comment by dmitriitux** [comment]
https://github.com/Quantum-Manager/quantummanager/commit/b28c560e8893fc6db1b94b572731fbf38a6d5e49
