### ISSUE TITLE
Действие вставки файла (копирование) и вставки в статью - переименовать

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#21]
![Screen Shot 2020-05-30 at 14 17 50](https://user-images.githubusercontent.com/3432048/83326948-c0a87300-a280-11ea-96e2-b91932650e2d.png)

есть действие "вставить файл" из буфера. а есть вставить в саму статью  -  условный insert image.
Действия разные, а название одно. 
Пусть уж будет Embed image - так понятнее, а в русском - Вставить в материал.

по привычке кнопку вставки ожидаешь увидеть внизу, рядом с кнопкой закрыть.

**Comment by Sulpher** [comment]
перенести тикет в feature request, тк это не баг, а улучшение.

**Comment by dmitriitux** [comment]
> ![Screen Shot 2020-05-30 at 14 17 50](https://user-images.githubusercontent.com/3432048/83326948-c0a87300-a280-11ea-96e2-b91932650e2d.png)
> 
> есть действие "вставить файл" из буфера. а есть вставить в саму статью - условный insert image.
> Действия разные, а название одно.
> Пусть уж будет Embed image - так понятнее, а в русском - Вставить в материал.
> 
> по привычке кнопку вставки ожидаешь увидеть внизу, рядом с кнопкой закрыть.

вставить материал не подходит, вызов может быть не только в материалах

**Comment by Sulpher** [comment]
тогда в русской версии можно оставить "вставить" для добавления файла и "вставить из буфера" - тут сразу все понятно

**Comment by dmitriitux** [comment]
поменял в локализации
