### ISSUE TITLE
Feature Request : Pexels

### ISSUE THREAD

**Issue by brianteeman** [Quantum-Manager/tracker#22]
**Is your feature request related to a problem? Please describe.**
The images from pexels.com are awesome and a much better option than pixabay or unsplash

**Describe the solution you'd like**
Integration with pexels in the same way as pixabay

**Describe alternatives you've considered**
No pexels integrations with joomla currently exist

**Additional context**
https://www.pexels.com/api/

**Comment by dmitriitux** [comment]
@brianteeman ok, I will release the integration soon, I myself recently thought about it

**Comment by brianteeman** [comment]
Awesome. Happy to test it.

**Comment by dmitriitux** [comment]
@brianteeman for two weeks somewhere, there are many tasks now

**Comment by dmitriitux** [comment]
@brianteeman added pexels, now there is a photo stock button, everything is there. This is not a release.
https://github.com/Quantum-Manager/start/releases/tag/1.5.3

**Comment by brianteeman** [comment]
woohoo - I will test it over the weekend

**Comment by brianteeman** [comment]
Random comments

Photostocks should be renamed Stock Photos
Is there supposed to be an icon before Photostocks

Otherwise all seems good 

# Thank you

**Comment by dmitriitux** [comment]
@brianteeman ok

**Comment by dmitriitux** [comment]
I close the issue. The new photo stock will be in the next release in a few weeks. If necessary, you can download intermediate versions here: https://github.com/Quantum-Manager/start/releases

**Comment by dmitriitux** [comment]
Here's how it happened:
<img width="276" alt="Снимок экрана 2020-08-01 в 23 25 57" src="https://user-images.githubusercontent.com/6643167/89109943-5eb9e480-d44e-11ea-8b5b-899bc7dde781.png">

**Comment by dmitriitux** [comment]
@brianteeman if interested, then study this button, this will make it easier to insert files into materials, documents, etc.
https://norrnext.com/docs/joomla-extensions/quantum-manager/editor-button

**Comment by brianteeman** [comment]
The button is on my list to check. First I have to create non uikit markup

**Comment by dmitriitux** [comment]
@brianteeman We released a release and there was an import/export of settings, including for the button plugin. Prepare you templates for boostrap? This will be a json file that you simply import into the plugin.
