### ISSUE TITLE
Автоматическое создание миниатюр

### ISSUE THREAD

**Issue by wedal** [Quantum-Manager/tracker#25]
**Ваше предложение связано с проблемой? Пожалуйста, опишите.**
Я всегда расстраиваюсь, когда приходится создавать миниатюру отдельно от основного изображения. Было бы здорово иметь опцию, например чекбокс или кнопку, которая позволяла бы создать миниатюру из основного установленного изображения в один клик. 

**Опишите решение, которое вы хотели бы**
Вот о чем речь:
![изображение](https://user-images.githubusercontent.com/14833679/88168093-ba5cc480-cc3b-11ea-90fe-7848b3ccc1cb.png)
Предположим, мы создаем каталог на материалах Joomla. У нас есть исходное изображение, полученное с фотоаппарата. Для сайта оно слишком велико и мы обрезаем его в менеджере до нужных размеров и выставляем в качестве основного. Но теперь нам нужно вырезать и выставить еще и миниатюру. Безусловно, возможность сделать это вручную должна оставаться, поскольку не всегда изображение миниатюры должно совпадать с основным. 
Но при этом хорошо бы иметь возможность сгенерировать миниатюру из основного изображения в один клик. Я вижу это так:
1) В настройках менеджера задаем размер/размеры(?) миниатюры. 
2) На вкладке материалов (или в окне менеджера) добавляем кнопку вроде: "Создать миниатюру из основного выбранного изображения". 

**Опишите альтернативы, которые вы рассмотрели**
Когда-то для решения этой задачи я использовал плагин https://extensions.joomla.org/extension/mavik-thumbnails/. Он решает эту задачу автоматически. Но не всегда требуется автоматическое решение. Создание миниатюры в один клик было бы предпочтительнее.

**Дополнительный контекст**
Открытым остается вопрос в месте хранения миниатюр в случае автоматической генерации.

**Comment by dmitriitux** [comment]
@wedal можно добавить сабформу в настройках (как пропорции) и там размеры указываются миниатюр. и потом в действиях просто появляется создать, или кнопка дополнительная с выпаданием с этими миниатюрами

**Comment by dmitriitux** [comment]
@wedal сделал, в новой версии будет эта функция
