### ISSUE TITLE
Ablity for front end users

### ISSUE THREAD

**Issue by philbertphotos** [Quantum-Manager/tracker#3]
Would be nice to have FrontEnd users be able to use the Media Manager when updating articles. Of course with a bit of security.

**Comment by Elfangor93** [comment]
Any news about the availability for the frontend?
Would be nice to have the button plugin and the media manager replacement inside the article editing form also in the frontend...

**Comment by dmitriitux** [comment]
> Any news about the availability for the frontend?
> Would be nice to have the button plugin and the media manager replacement inside the article editing form also in the frontend...

about the front is not yet clear. And the insert buttons are already there: https://www.norrnext.com/docs/joomla-extensions/quantum-manager/editor-button

**Comment by Sulpher** [comment]
The front-end support added in version 2.0.0:
 https://www.norrnext.com/blog/item/quantum-manager-2-0-released

The topic can be closed.
