### ISSUE TITLE
Setting default user path for year/month

### ISSUE THREAD

**Issue by danjde** [Quantum-Manager/tracker#30]
Hi Devs!
Is is possible with Quantum Manager set a default upload/browse user/group directory path with the current year, and eventual month?
Making it possible to automatically create directories and subdirectories based on the year and optionally on current month and again always allowing the user to go back to the root image directory if desired.

Thanks!

Davide

**Comment by dmitriitux** [comment]
@danjde Hi.

Yes, you can do it. In the image scope, specify the path you need with the variables. Then create your own scope called "All images" and point to "images".
<img width="935" alt="Снимок экрана 2020-08-10 в 22 21 59" src="https://user-images.githubusercontent.com/6643167/89821860-f22e9c00-db57-11ea-95d3-2339a475806f.png">
<img width="929" alt="Снимок экрана 2020-08-10 в 22 22 17" src="https://user-images.githubusercontent.com/6643167/89821887-fbb80400-db57-11ea-967a-7e56a59adac5.png">


Next, we have "Profiles", where you can override scopes from the acl group. 
Documentation: https://norrnext.com/docs/joomla-extensions/quantum-manager/component-options/profiles

One of these days we will have a new release soon and there will be import and export of manager settings, if you don’t understand, we can send you an example of a configuration, and then you will import it.

**Comment by danjde** [comment]
WAW! Seems very very complete!
Tomorrow (now is late here in Italy) I will try and let you know ;-)

Many thanks!

Davide

**Comment by danjde** [comment]
WAW! Seems very very complete!
Tomorrow (now is late here in Italy) I will try and let you know ;-)

Many thanks!

Davide

**Comment by dmitriitux** [comment]
@danjde ok, if it doesn't work, then write

**Comment by danjde** [comment]
Hi @dmitriitux, and firstly thank you for making such excellent work available to the community! Very impressive your work!

Secondly, two things:

1) is it possible to hook the JCE Image button to your Quantum media system?
2) Is it possible that every time user access the media he is placed in the default directory "foo"? I have seen that instead it happens that it is placed inside the last visited directory.

These two things are very important for users who are not very skilled in the use of these tools, maybe they are excellent writers, but do not have excessive confidence with the computer medium ;-)

Thanks again!

Davide
Italy

**Comment by dmitriitux** [comment]
@danjde 
1. to embed in JCE editor did not study, but the quantum button embed files is always at the bottom (docs: https://norrnext.com/docs/joomla-extensions/quantum-manager/editor-button)
2. you can disable the jce plugin that predefines com_media, then the quantum manager will be called. After disabling the plugin - the "image" button will always call the quantum
3. but so that he only opens "foo" - no. I did not consider this possibility. He remembers where the user was, and if this scope is available, then he tries to open it. It will be necessary to make such an opportunity to prioritize which areas to open

**Comment by danjde** [comment]
1. perfect! Do you know if is it possible to add a custom button into JCE toolbar, pointing to Quantum button embed files? I've seen this: https://github.com/widgetfactory/jce-custom
2. I've disabled all JCE plugins but clicking on JCE image icon, still start JCE media browser and not Quantum, but this could not be a big problem if could be possible to integrate into JCE toolbar quantum media browser. Actually, Quantum embed button (with JCE active) is positioned at the bottom, under the writing area and not inside the toolbar.
3. no problem, I've seen that with a logout and login, Quantum come back to the "foo" directory"


Thanks again!

Davide

**Comment by dmitriitux** [comment]
@danjde understood, I will add a button to jce via release. And in the jce itself, only their manager is called, this is not overridden, only add your own button

**Comment by danjde** [comment]
Given your kind availability, if you want I can help translate the interface into Italian, tell me the files I need to edit ;-)


Davide

**Comment by dmitriitux** [comment]
@danjde thanks, here is a link for translation: https://www.norrnext.com/quantum-manager-localizations

But it seems like Italian is already there.

**Comment by danjde** [comment]
Speechless, really!
But, never say never:

![Schermata da 2020-08-11 16-23-52](https://user-images.githubusercontent.com/4129294/89909348-420c7200-dbef-11ea-886a-bd988ed54a5f.png)

this above is not in Italian, i've find where this word could be placed with no luck..

;-)


Davide

**Comment by danjde** [comment]
If I try to contribute into https://www.norrnext.com/quantum-manager-localizations, obtain: error 404 Page not found..

**Comment by dmitriitux** [comment]
> If I try to contribute into https://www.norrnext.com/quantum-manager-localizations, obtain: error 404 Page not found..

I also have problems so far, it works through vpn, it will probably be restored later

**Comment by dmitriitux** [comment]
link on Italian language: https://www.norrnext.com/quantum-manager-localizations/quantum-manager/it-IT

but translated using this service:
https://www.transifex.com/norrnext/quantum-manager/

**Comment by danjde** [comment]
I think to have found a bug: 
enabling "Custom Scopes" -> Name: "Tutte le immagini" ; Folder: 'https://www.mysite.org/ images' seems impossible to embed file out of the Default Scopes path.
Simply the button "Embed" does not take any action!

Using:
Firefox 78.0.2
Joomla! 3.9.20 
PHP 7.3 
mysql  Ver 15.1 Distrib 10.3.18-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2


![Schermata da 2020-08-11 16-30-56](https://user-images.githubusercontent.com/4129294/89910179-353c4e00-dbf0-11ea-809e-662623d6e20d.png)

**Comment by dmitriitux** [comment]
@danjde switched to Italian, yes, a mistake, I will study and correct it

**Comment by dmitriitux** [comment]
@danjde understood, look, the scope was added, but it was not in the button plugin settings, you need to go to the button plugin settings and at least once to save with a new scope. I need to think about how to solve it

**Comment by dmitriitux** [comment]
> Speechless, really!
> But, never say never:
> 
> ![Schermata da 2020-08-11 16-23-52](https://user-images.githubusercontent.com/4129294/89909348-420c7200-dbef-11ea-886a-bd988ed54a5f.png)
> 
> this above is not in Italian, i've find where this word could be placed with no luck..
> 
> ;-)
> 
> Davide

if you have the opportunity, then connect to the translation, please, there will be a new release soon and the translation will need to be updated there.

Thanks.

**Comment by dmitriitux** [comment]
here (https://github.com/Quantum-Manager/start/releases/tag/1.5.3RC4), I put together a new release build, you can see (better in English)


changelog:
[new] Added integration with Pexels photo stock
[new] All photo stocks moved to "Stocks" button
[new] You can create preview templates and generate by button (the button appears in the toolbar when files are selected)
[new] You can override the file icon colors in the manager settings
[new] Added ability to import Quatum Manager component and plugin settings
[new] Added integration with SP Page Builder
[fixed] When inserting by the "Images" button, positioning of the image was not inserted
[fix] Removed "Allow downloading archives" setting, added a new "check archive contents" setting instead
[fix]] Added new settings for image meta tags. Added new jpel library (https://github.com/Quantum-Manager/jpel) (jpg formats supported)

**Comment by danjde** [comment]
> if you have the opportunity, then connect to the translation, please, there will be a new release soon and the translation will need to be updated there.
> 
I've try, but obtain again 404 error: https://www.transifex.com/norrnext/quantum-manager/language/it-IT/ :-(

**Comment by danjde** [comment]
Hi @dmitriitux 
I've try to access to root image folder (enabling "Custom Scopes" -> Name: "Tutte le immagini" ; Folder: 'https://www.mysite.org/ images') and it works only from "immagine" button, but not from "Embed Files", as screenshot shown:

![Schermata da 2020-08-12 10-46-52](https://user-images.githubusercontent.com/4129294/89995778-420d8000-dc8a-11ea-9a8a-88e13dc76863.png)

**Comment by danjde** [comment]
Excuse me again @dmitriitux,
but I've not understand what is it possible to do for attach the JCE image icon button to Quantum. Do you think it possible? It's not urgent ;-)

![Schermata del 2020-08-12 10-56-45](https://user-images.githubusercontent.com/4129294/89996782-86e5e680-dc8b-11ea-85b8-37fa946163a7.png)


Thanks again!

**Comment by dmitriitux** [comment]
> Excuse me again @dmitriitux,
> but I've not understand what is it possible to do for attach the JCE image icon button to Quantum. Do you think it possible? It's not urgent ;-)
> 
> ![Schermata del 2020-08-12 10-56-45](https://user-images.githubusercontent.com/4129294/89996782-86e5e680-dc8b-11ea-85b8-37fa946163a7.png)
> 
> Thanks again!

yes, I'll make the button in a couple of releases

**Comment by dmitriitux** [comment]
> Hi @dmitriitux
> I've try to access to root image folder (enabling "Custom Scopes" -> Name: "Tutte le immagini" ; Folder: 'https://www.mysite.org/ images') and it works only from "immagine" button, but not from "Embed Files", as screenshot shown:
> 
> ![Schermata da 2020-08-12 10-46-52](https://user-images.githubusercontent.com/4129294/89995778-420d8000-dc8a-11ea-9a8a-88e13dc76863.png)


The scope was added, but it was not in the button plugin settings, you need to go to the button plugin settings and at least once to save with a new scope. I need to think about how to solve it

**Comment by danjde** [comment]
> yes, I'll make the button in a couple of releases

Well, so I wait for the JED reviews, so I can only write positive notes, that users then will be able to confirm ;-)
Quantum Manager seems to me to be a great job, little miss to making it perfect!


Davide

**Comment by dmitriitux** [comment]
@danjde ok, thanks. I close this issue.
