### ISSUE TITLE
Could be possible "Embeding Files" add video content?

### ISSUE THREAD

**Issue by danjde** [Quantum-Manager/tracker#34]
Hi Devs and thanks again fro your wonderful Joomla component!!
I would like to know if is it (or will be) possible to embed video content into article using Quantum.

Thanks!

Davide

**Comment by dmitriitux** [comment]
@danjde yes, docs: https://norrnext.com/docs/joomla-extensions/quantum-manager/editor-button

**Comment by dmitriitux** [comment]
We have our own plugin that adds a button, you asked a question like in the past, with the help of it. Write your html in the template and paste

**Comment by danjde** [comment]
Yes, I've read the documentation, and I've look into "Button - Embed Files (Quantum Manager) plugin", where I can find the Video template, along with many others, but why I've not the drop down video (and others) choice?

![Schermata del 2020-08-20 17-06-53](https://user-images.githubusercontent.com/4129294/90790624-92c74d80-e308-11ea-9d45-157006faba17.png)

And here (into the "Button - Embed Files Quantum Manager plugin",) all options seems fine: 

![Schermata da 2020-08-20 17-08-19](https://user-images.githubusercontent.com/4129294/90790786-bbe7de00-e308-11ea-874b-f40c3e1fef0e.png)

**Comment by dmitriitux** [comment]
enable the video scope in the component setting

**Comment by danjde** [comment]
Hi @dmitriitux and thanks thanks again for your precious help!
My system is configured for accept all media kind, as image below:

![Schermata del 2020-08-20 18-49-07](https://user-images.githubusercontent.com/4129294/90801693-8649f180-e316-11ea-9fd8-8872a4ca733b.png)

But nevertheless I can only embed image file, no other drop down choice:

![Articoli: Nuovo - riusa eu - Amministrazione - Mozilla Firefox_001](https://user-images.githubusercontent.com/4129294/90801848-b72a2680-e316-11ea-95fa-b31a81744f4c.jpg)

Where I'm wrong?

**Comment by dmitriitux** [comment]
@danjde hmm, I need to check, I'll write a little later

**Comment by danjde** [comment]
Don' worry, be quite, covid permitting, no one escapes :-D

Thanks!

**Comment by dmitriitux** [comment]
@danjde remembered, look, you need to switch to the "Video" scope in the manager, then the template starts working

**Comment by dmitriitux** [comment]
all templates are assigned to the scope

**Comment by dmitriitux** [comment]
if you have video in "images" folder, just change in the component settings - the path for the video scope to the "images" folder instead of "videos:

**Comment by danjde** [comment]
On component I've video path: 

`images/{year}`

Scope name:

`Video`

On Plugin I've scope name:

`Videos`

and template name:

`Video`

> remembered, look, you need to switch to the "Video" scope in the manager, then the template starts working

Excuse me but I don't understand what you want to tell me.

> if you have video in "images" folder, just change in the component settings - the path for the video scope to the "images" folder instead of "videos:

I've done so, or I'm wrong? Do you see my screenshot?

Thanks again!

**Comment by danjde** [comment]
Hi @dmitriitux, excuse me again, could you clarify better how to proceed? I'm sorry, but I can't go any further.
if there were some practical examples in the documentation of how to enable the video template would be useful to many people I think.

Thanks again!

Davide

**Comment by dmitriitux** [comment]
@danjde when you paste into the editor, you need to switch to the video scope, then the templates from the video will work in the select

**Comment by dmitriitux** [comment]
@danjde happened?

**Comment by danjde** [comment]
Hi @dmitriitux the problem is still upstream: I cannot see any other drop down choice than "image".

![Articoli: Nuovo - riusa eu - Amministrazione - Mozilla Firefox_001](https://user-images.githubusercontent.com/4129294/90980330-ef21ab80-e55a-11ea-9775-b738fd906c53.jpg)

The plugin button Incorporare files (Quantum Manager) is enabled and all seems fine.
In the backend Quantum Manager, all predefined scope options are enabled.
But I still don't see other choices from the editor embed button.

Could be could it depend on the fact that the videos are stored in the same directory as the images and documents or on the fact that he added the path of the current year: 

`mysite.com/images/{year}`

 ?

Thanks again!

**Comment by dmitriitux** [comment]
ok, I will record a video as I can and throw it off

**Comment by dmitriitux** [comment]
@danjde Here's a video: https://cloud.mail.ru/public/iWkk/3Fw8EBR96 

1. put the folder of the video scope on the "image"
2. when you insert a video into an article, you select the video scope, and then the file

**Comment by danjde** [comment]
At the end you did it! Were you able to make me understand how to do it!!
**I't's not necessary to select from drop down menu the the file type, but depending on which directory the file is taken from, the template is activated**

I think that this description should be added to your documentation, because users (a bit dumb like me) may encounter difficulties and perhaps consider the software incomplete or with bugs!
I think very important to clarify this procedure!

In any case, thank you for your patience and for the help you have provided me, thank you so much!!

Issue closed for me

**Comment by dmitriitux** [comment]
ok, we will fix documentation
