### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by jfquestiaux** [Quantum-Manager/tracker#35]
**Describe the bug**
When enabling the "System - Redirect Media (com_media) call to Quantum Manager" plugin, I get this JS error when I write/edit an article and the intro/main image field is not displayed:

System - Redirect Media (com_media) call to Quantum Manager

If I disable the plugin, I can add (the usual way) an intro/main image to the article

**To Reproduce**
1. Go to Content > Add article > New (or Edit)
2. See error

**Expected behavior**
Possibility to add intro/main images

**Screenshots**
![screenshot_782](https://user-images.githubusercontent.com/1868381/90957562-7d7c2b80-e48e-11ea-8805-bbd69739bb09.jpg)

**System Information (please complete the following information):**
 - Extensions version : 1.5.2
 - PHP version: 7.4.8
 - Server OS: CentOS 7 - LiteSpeed server + LSCache 1.31
 - Browser: Firefox

**Additional context**
I tried to disable several system plugin (YooTheme, LSCache, JCH Optimizer, JQuery Easy, DropFiles, EngageBox), but with no results

**Comment by dmitriitux** [comment]
can you throw off the error itself?

**Comment by jfquestiaux** [comment]
![screenshot_783](https://user-images.githubusercontent.com/1868381/90957892-ccc35b80-e490-11ea-9c86-3956f1f21b65.jpg)

**Comment by dmitriitux** [comment]
this plugin has a function to "Replace Media Field", try to enable the plugin, but disable the "replace" in the plugin settings. I will study the problem

**Comment by jfquestiaux** [comment]
Yes, I tried that but, as far as I can tell, it's the same as disable the plugin: no error but no Quantulm management either.
It's probably something related to thsi particular site (the ListeSpeed server?) because I don't have this on others sites I manage, but I haven't had the time to investigate further.

**Comment by dmitriitux** [comment]
> Yes, I tried that but, as far as I can tell, it's the same as disable the plugin: no error but no Quantulm management either.
> It's probably something related to thsi particular site (the ListeSpeed server?) because I don't have this on others sites I manage, but I haven't had the time to investigate further.

it may well be, maybe he is filtering something there

**Comment by it7steve** [comment]
I have exactly the same issue. Quantum was working fine until site migrated to a server using LiteSpeed.
Have ou found the solution ?
Thanks

**Comment by dmitriitux** [comment]
@it7steve @jfquestiaux I do not have time to deploy and study how to set the server configuration to litespeed, can you select a polygon for me so that I can see what the problems are?

**Comment by dmitriitux** [comment]
or you can send me access to the admin panel of your site access can be sent by mail: cymbal@delo-design.ru

**Comment by jfquestiaux** [comment]
Hi Dmitri,
I just created you a Super User access to the site with the email address in your previous post.

**Comment by dmitriitux** [comment]
> Hi Dmitri,
> I just created you a Super User access to the site with the email address in your previous post.

ok, I see, but I can enter a chat with you somewhere to be with you now in online communication?

**Comment by dmitriitux** [comment]
skype, telegram, whatsapp or etc

**Comment by jfquestiaux** [comment]
Skype : jfquestiaux

**Comment by dmitriitux** [comment]
the component com_fabrik was to blame, it rewrote the core joomla FormFIeld class, removed a couple of important lines and therefore the field from the file manager could not load
https://github.com/Quantum-Manager/quantummanager/commit/e4e9bf88b7e453cd6dd496c7e8a65f95d624af1c
