### ISSUE TITLE
Предупреждение ниже окошка поиска в стоках и loading bar

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#37]
вывести предупреждение ниже поисковой строки.
предупредить о размерах картинок и вероятных задержках при загрузке изображения.
ёмкой фразой.

ещё заметил: когда выбираю любой фотосток и просто жду, то секунд через 8 появляются случайные картинки. надо тогда прогресс бар вывести, чтобы понимать, что идет какой-то процесс

**Comment by dmitriitux** [comment]
https://github.com/Quantum-Manager/quantummanager/commit/b1503636b0cf33ec9c3d31838e5f317dd938bc85
https://github.com/Quantum-Manager/quantummanager/commit/5e2dea99dc7ed52d7bbddffc456a633bb6be90c6
https://github.com/Quantum-Manager/quantummanager/commit/6ed6d528aa11d8ddc816116c5db764689fef3c28
