### ISSUE TITLE
Ссылка на локализации в окошке помощи - link to Localizations in help

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#38]
Добавить ссылку на локализации после Product page:
 
![chrome_KJVEqPiJJD](https://user-images.githubusercontent.com/3432048/91324271-8e000f00-e7ca-11ea-8618-04e27c055d90.png)

Это поможет людям найти локализацию. 

В пост-установочном сообщении тоже предлагаю добавить ссылку на локализации и стилистически сделать броской, если там этого еще нет.

**Comment by dmitriitux** [comment]
https://github.com/Quantum-Manager/quantummanager/commit/a2dacded870ec3993e8f8010b521541b811c487e
