### ISSUE TITLE
No picture preview on v 1.6.0

### ISSUE THREAD

**Issue by GitUpAndRun** [Quantum-Manager/tracker#40]
**Describe the bug**
When browsing the file navigation window in the Quantum Manager no previews of the pictures are displayed.
Only the file icons with their file extension (i.e. grey with "jpg" or "png") are displayed as shown in the screenshot below.
I am not sure if this is a bug or just a missing setting - but after a long time of searching how to get this done i decided to report this here and get some help on it.

**To Reproduce**
1. Use Joomla! 3.9.21
2. Install package 1.6.0
3. Go to Components > Quantum Manager > any image folder

**Expected behavior**
The expected behavior is that at least for jps or png a preview of the picture is displayed.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/71545944/93662924-0e313180-fa64-11ea-95cf-e90c06f257b4.png)

**System Information (please complete the following information):**
 - Quantum Manager Package 1.6.0
 - PHP version: 7.2.33
 - Server OS: [Linux]
 - Browser chrome
 - Joomla! 3.9.21

BR

**Comment by dmitriitux** [comment]
@GitUpAndRun Hi,
Can you upload to a cloud service and drop these files?

**Comment by GitUpAndRun** [comment]
> @GitUpAndRun Hi,
> Can you upload to a cloud service and drop these files?

What files exactly do you require?
Do you mean the actual install ressources that I used to install the component?

**Comment by b2z** [comment]
Do you have any errors in the browser console?

**Comment by GitUpAndRun** [comment]
> Do you have any errors in the browser console?

No, there are no errors or any other strange behavior. It looks all quite normal - except the missing previews.

**Comment by dmitriitux** [comment]
> > @GitUpAndRun Hi,
> > Can you upload to a cloud service and drop these files?
> 
> What files exactly do you require?
> Do you mean the actual install ressources that I used to install the component?

the pictures themselves that don't work

**Comment by dmitriitux** [comment]
<img width="1290" alt="Снимок экрана 2020-09-19 в 15 49 54" src="https://user-images.githubusercontent.com/6643167/93667580-c88a5e00-fa8f-11ea-9194-8230e1ae3b77.png">
I don't have such problems.
Here are either pictures or server settings

**Comment by b2z** [comment]
May be **_thumbs** folder is missing (cannot be created or something like that)?

**Comment by GitUpAndRun** [comment]
I installed a dedicated, fresh J! 3.9.21 with it's own database and just added QUANTUM via direct install from the J extensions installer.

- Joomla: 3.9.21
- PHP: 7.4 (see phpinfo(): [PHP_Info_7.4.10.pdf](https://github.com/Quantum-Manager/tracker/files/5254245/PHP_Info_7.4.10.pdf))
- Host: IONOS
- DB: MySQL 5.7 / MySQLi
- Browser: Chrome / Edge

@dmitriitux: 
I used maximum size pictures from unsplash to test it. For example [this](https://unsplash.com/photos/7ghPaPLdmTY).
The beahvior is the same, indifferent if you search any picture from the quantum unsplash search or if you upload it from your local machine.

@b2z:
Folders _thumbs and _original are created automatically without any problems
![image](https://user-images.githubusercontent.com/71545944/93747759-72d0c580-fbf7-11ea-82d4-26c94c49cc5a.png)

**Comment by GitUpAndRun** [comment]
Update:

I kept on trying and found out the following behavior...

**1. Uploading an picture in the file format \*.webp shows a thumbnail.**
<img src="https://user-images.githubusercontent.com/71545944/94288951-55ce2680-ff58-11ea-9f80-9d4940024c6f.png" width="500">

**2. Uploading a WEBP-file with the same filename of an already existing JPG in the same folder shows the thumbnail of the WEBP and the JPG after reloading the view!**
It does not matter which filename you use. Even if two pictures are not the same, when the same filename is used the thumbnail of the *webp is applied to the *.jpg.

  Aafter upload, before page reload:
<img src="https://user-images.githubusercontent.com/71545944/94289387-ee64a680-ff58-11ea-810d-a866d26ffb4a.png" width="500">
After page reload:
<img src="https://user-images.githubusercontent.com/71545944/94289430-fde3ef80-ff58-11ea-85c8-f6cf8bcd8a26.png" width="500">
**3. After deleting the \*.webp file the thumbnail of the JPG file remains - until clearing the Joomla Cache.** 

**4. After clearing the Joomla cache also the JPG previews disappier again.**

Strangely enough - Activating / diabling the Joomla System Cache does not change this bahavior.

Hopefully this helps further...

**Comment by b2z** [comment]
@GitUpAndRun 
> Folders _thumbs and _original are created automatically without any problems

In this folders you have the same problem?

**Comment by GitUpAndRun** [comment]
Yes, its the same behavior there

![image](https://user-images.githubusercontent.com/71545944/96117909-12c5fa00-0eeb-11eb-9dce-bbf980bf8b30.png)

![image](https://user-images.githubusercontent.com/71545944/96117899-0fcb0980-0eeb-11eb-850e-a51947d2433f.png)


![image](https://user-images.githubusercontent.com/71545944/96117884-0c378280-0eeb-11eb-8568-ccbaad2cec5c.png)

**Comment by dmitriitux** [comment]
@GitUpAndRun Can you give me access to this site or to a site where there is a similar problem? I'll take a look at this error. I can't catch it, maybe there is some uniqueness in the configuration of your server

**Comment by GitUpAndRun** [comment]
@dmitriitux 
Yes i will prepare something and let you know as soon it is ready.

**Comment by dmitriitux** [comment]
ok, you can send accesses to cymbal@delo-design.ru

**Comment by GitUpAndRun** [comment]
@dmitriitux:
Thank you for taking care of this issue.
I sent you the access to a demo site by email.

**Comment by dmitriitux** [comment]
This was due to getting the memory_limit parameter in php, returning -1 instead of specifying in dimensions. When generating a preview, Quantum checks if it has enough memory to create a preview.
In release 1.6.1 will be fixed

https://github.com/Quantum-Manager/quantummanager/commit/d32c7492ee0f033aaafa03313a25c87c298160b8
