### ISSUE TITLE
Проверка прав на папки и выводить иконку с замочком

### ISSUE THREAD

**Issue by Sulpher** [Quantum-Manager/tracker#45]
У папки по некоторым причинам могут быть неправильные права на чтение. 
Нужно сделать проверку и выводить такую папку  с полупрозрачностью самой папки и с  иконкой замочка (без прозрачности - иконка папки будет приглушена, а икнока замочка более четкая).

**Comment by progreccor** [comment]
если у папки неправильные права на чтение - она не может быть прочитана. то есть недоступна скрипту.
если проблемы с правами на запись - квантум и так это показывает

**Comment by dmitriitux** [comment]
> если у папки неправильные права на чтение - она не может быть прочитана. то есть недоступна скрипту.
> если проблемы с правами на запись - квантум и так это показывает

в том и прикол, что иногда не читает, php фукнция is_writeable как-то интересно отрабатывает

**Comment by progreccor** [comment]
writeable  это права на запись.
Евгений спрашивал про права на чтение....

**Comment by Sulpher** [comment]
> writeable это права на запись.
> Евгений спрашивал про права на чтение....

правильный вопрос тогда звучит так: в случае некорректных прав у папки, Quantum не мог построить древо каталога.
уже воспроизвели, Дима доп.проверку внесет.
то есть, если по каким-то причинам у папки неправильные права, то компонент некорректно работает.

**Comment by dmitriitux** [comment]
замок тогда надо отображать если не доступно для чтения и для записи
