### ISSUE TITLE
icon preview not work after joomla update

### ISSUE THREAD

**Issue by revolt73** [Quantum-Manager/tracker#47]
Hi
after the latest update to the latest version of joomla 3.9.22, the thumbnails of the icons in the media manager are not displayed.

I am attaching files to view the anomaly

Thanks
![screen](https://user-images.githubusercontent.com/72993632/96611512-08499d00-12fd-11eb-8dec-57f53746ed44.png)

**Comment by dmitriitux** [comment]
hi,
Do you have a memory_limit (php parameter) value of -1? If so, release 1.6.1 will fix everything

**Comment by revolt73** [comment]
Yes

Il dom 25 ott 2020, 15:30 Dmitrii Cymbal <notifications@github.com> ha
scritto:

**Comment by dmitriitux** [comment]
OK, then just wait for 1.6.1 release. There's a fix.
It was described here why: https://github.com/Quantum-Manager/tracker/issues/40

**Comment by b2z** [comment]
:+1:
