### ISSUE TITLE
Error after package install

### ISSUE THREAD

**Issue by cr8on** [Quantum-Manager/tracker#49]
**Describe the bug**
Immediately after an Install from Web install completes, there is an error highlight shown
"Error: PKG_QUANTUMMANAGER_LIBFIELDS_INSTALLATION_ERROR"

**To Reproduce**
1. Go to 'Install from Web'
2. Search for Quantum Manager package
3. Click on and install package
4. After the package install completes, there is an error message, as described above, as well as an install success message.

**Expected behavior**
No error is shown after install

**System Information (please complete the following information):**
 - Extensions version: 1.6.1
 - PHP version: 7.3
 - Server OS: Linux (CentOS 7 with Cpanel/WHM)
 - Browser : Firefox-based (Palemoon)

**Comment by dmitriitux** [comment]
The manager remotely downloads the field library from the server. Apparently you have a ban on remote downloading. Install this library manually. Link: https://github.com/JPathRu/lib_fields/releases/tag/1.2.1

**Comment by cr8on** [comment]
Thank you.
I did some troubleshooting, and it looks like I had allow_url_fopen and allow_url_include disabled in php.ini, and this was likely the cause of not getting the library. This was also causing the stock photo integrations to download empty files.

**Comment by dmitriitux** [comment]
@cr8on Yes, the integration of photo stocks refers to our server, which then receives information from photo stocks.

**Comment by dmitriitux** [comment]
and I have to create a constant, I forget about it all the time :)
