### ISSUE TITLE
Как открыть корневую директорию сайта?

### ISSUE THREAD

**Issue by AlexZibin** [Quantum-Manager/tracker#51]
**Ваше предложение связано с проблемой? Пожалуйста, опишите.**
(Сабж)

**Опишите решение, которое вы хотели бы**
Добавьте Root в Default Scopes. Через Custom Scopes никак не получается. Документация Quantum Manager не открывается, поэтому почитать негде.

**Comment by b2z** [comment]
Никак. Это прежде всего файловый менеджер медиа файлов, а не файловый менеджер всего.

**Comment by dmitriitux** [comment]
@AlexZibin добавьте свою область и путь ей просто слеш "/"

**Comment by dmitriitux** [comment]
> Никак. Это прежде всего файловый менеджер медиа файлов, а не файловый менеджер всего.

нет, открыть можно, просто это не описано нигде.

**Comment by dmitriitux** [comment]
надо подумать как вынести это в документацию, я этот issue тогда закрываю
