### ISSUE TITLE
Unable to replace SP Page Builder media manager

### ISSUE THREAD

**Issue by toonetcreation** [Quantum-Manager/tracker#52]
**Describe the bug**
Even if I select sp page builder inside quantum, the default sp page builder media manager is displayed instead of quantum GUI.
See attached file.
What's wrong? or what I missed ?

**Screenshots**
![2020-11-21_00-37-14](https://user-images.githubusercontent.com/20813754/99859983-055afa00-2b92-11eb-8ff2-fe7b661ab521.jpg)

**System Information (please complete the following information):**
 - Extensions version 1.6.1
 - PHP version: 7.4.12
 - Server OS: Linux
 - Browser [e.g. firefox, chrome, safari, ie]

**Comment by dmitriitux** [comment]
@toonetcreation integration with quantum and SP builder is responsible for another plugin. It is called "Integration of Quantum Manager with SP builder". Turn it on

**Comment by toonetcreation** [comment]
@dmitriitux yes I have already enabled this plugin, same problem.

**Comment by dmitriitux** [comment]
@toonetcreation which version of the sp builder?

**Comment by toonetcreation** [comment]
@dmitriitux latest release 3.7.6

**Comment by dmitriitux** [comment]
@toonetcreation can you send me sp builder pro by email? This is not my main tool and I do not buy it. 
Email: cymbal@delo-design.ru

**Comment by toonetcreation** [comment]
There is no email ton contact them directly, only ticket support system if you are a customer or this form if you're not : https://www.joomshaper.com/contact

I can send to you the sp page builder package if you prefer?

**Comment by toonetcreation** [comment]
Another info : works fine from back-end, but not from front-end.

**Comment by dmitriitux** [comment]
@toonetcreation ah, I got it. Quantum does not work at the front. But you can make general sessions, then the admin panel and the front will have one common session and the override on the front will work

**Comment by toonetcreation** [comment]
yes works fine now.
you can close this case.
many thanks
