### ISSUE TITLE
Сортировка папок и файлов

### ISSUE THREAD

**Issue by triode-master** [Quantum-Manager/tracker#53]
Очень огорчает отсутствие сортировки. У меня много папок, к примеру от 1 до 100, я создаю 101 и чтобы до неё добраться мне надо прокрутить вниз. Подскажите как сделать обратную сортировку, чтобы 101 папка была в самом верху.

**Comment by dmitriitux** [comment]
@triode-master да, есть такой косяк, пока никак, надо мне написать, я планировал сделать в табличном виде сортировку по полям, еще не добрался до этого

**Comment by dmitriitux** [comment]
добавлено в 2.0.0
