### ISSUE TITLE
Не работает плагин "Кнопка - Встраивание файлов (Quantum Manager)"

### ISSUE THREAD

**Issue by antatmedia** [Quantum-Manager/tracker#54]
**Опишите ошибку**
При попытке вставить файл в статью или товар, открывается пустое модальное окно, а в консоли ошибка 

`Mixed Content: The page at 'https://site.ru/administrator/index.php?option=com_content&view=article&layout=edit&id=55' was loaded over HTTPS, but requested an insecure frame 'http://site.ru/administrator/index.php?option=com_ajax&plugin=quantummanagerbutton&group=editors-xtd&format=html&&plugin.task=getmodal&e_name=jform_articletext&asset=com_content&author=9a548abcbb53119c5185ac29c4221558=1&function=function()%7b%7d'. This request has been blocked; the content must be served over HTTPS.`

**Как воспроизвести**
Шаги для воспроизведения ошибки:
1. Зайти в редактирование любой статьи
2. Нажать кнопку "Добавить файл"

**Ожидаемое поведение**
Ожил в модальном окне увидеть форму загрузки и вставки картинки

**Скриншоты**
https://yadi.sk/i/Ibu7VMwKGDCz8Q

**Информация о системе (пожалуйста, заполните следующую информацию):**
  - Версия Расширения 1.6.1
  - Версия PHP: 7.4.4
  - ОС Сервера: Linux 
  - Браузер  chrome

**Дополнительный контекст**
Понятно что проблема в HTTPS в настройках htts включен для всего сайта.
А так же в конфиге прописаны $live_site и $force_ssl = '2';
В общем сделано всё по этой https://joomla.center/baza-joomla/zaschita-joomla/ssl-https-joomla инструкции

Помогите решить проблему.

**Comment by dmitriitux** [comment]
@antatmedia ок, через пару часов постараюсь посмотреть

**Comment by dmitriitux** [comment]
@antatmedia а по кнопке вставить модуль открывается модальное окно?

**Comment by dmitriitux** [comment]
@antatmedia вам надо редирект как минимум на сайте поставить с http на https. Это решит проблему, но все равно будет выгружаться http, но будет перенаправлять. Я посмотрел в коде плагина, конечную ссылку генерирует сама джумла, мне надо там закопаться и посмотреть почему выгружается http

**Comment by antatmedia** [comment]
@dmitriitux переадресация в .htaccess стоит, и работает, но всё равно открывается пустое модальное окно.

**Comment by antatmedia** [comment]
Проблема решена. Проблема не в вашем плагине. В htaccess было неправильно написанное правило, которое ломало перенаправление. Большое спасибо!
