### ISSUE TITLE
Help remove QM from Joomla! site

### ISSUE THREAD

**Issue by gandsnut** [Quantum-Manager/tracker#56]
**Describe the bug**
When I disable then uninstall QM from my 3.9x Joomla! site, I now cannot access "Extensions -> Manage -> Manage" and get an error page.

**To Reproduce**
1. Go to Extensions -> Manage -> Manage
2. Find the QM component
3. Check-mark to disable
4. Check-mark to select QM component
5. Choose 'Trash'

Any future visit to Extensions -> Manage -> Manage page fail.

**Expected behavior**
I expect the component to be uninstalled completely and to be allowed back into Extensions -> Manage -> Manage

**Screenshots**

![quantummanagerhelper_not_found](https://user-images.githubusercontent.com/29338195/101590230-a679eb00-39af-11eb-81e9-7c1ee1b8f6a8.png)

**System Information (please complete the following information):**
 - Extensions version Current version
 - PHP version: Unknown (hosted server)
 - Server OS: Unknown (hosted server)
 - Browser Chromium

**Additional context**

**Comment by dmitriitux** [comment]
@gandsnut ok, I'll study the problem. Try to remove only the package, the package itself will remove unnecessary extensions

**Comment by dmitriitux** [comment]
if it doesn't, then try to install the package again and then select the package and remove only it

**Comment by gandsnut** [comment]
Re-install then delete package (NOT component) works.  Thank you.

**Comment by dmitriitux** [comment]
@gandsnut please tell me why you deleted. Are you missing something or is something not working correctly?

**Comment by gandsnut** [comment]
At least for the near future, I am going back to a simpler, no-addon way
of adding links to media, into articles, is quicker.  The idea of, what
is it, 'scope', is difficult to grasp.

---

On 12/11/2020 06:03, Dmitrii Cymbal wrote:

> @gandsnut [1] please tell me why you deleted. Are you missing something or is something not working correctly? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/gandsnut
[2]
https://github.com/Quantum-Manager/tracker/issues/56#issuecomment-743154844
[3]

**Comment by dmitriitux** [comment]
@gandsnut ok
