### ISSUE TITLE
Integration with SP PageBuilder - Doesn't work ?

### ISSUE THREAD

**Issue by pcombet-adosis** [Quantum-Manager/tracker#58]
Hello,
thank you for the fantastic job done !
I can't make work **Quantum Manager** with **SpPageBuilder**. I have added in the Plugin > Redirect Media > all the SppageBuilder entries (SpPageBuilder:Media, SpPageBuilder:Page, SpPageBuilder:Pages...) But when selecting SPPageBuilder page, I don't have the Quantum Manager . How do you fix it ?
Thanks,
Philippe

Joomla 3.9.21, PHP 7, new website, no fancy configuration

**Comment by dmitriitux** [comment]
@pcombet-adosis read here: https://github.com/Quantum-Manager/tracker/issues/52

**Comment by pcombet-adosis** [comment]
@dmitriitux Thx, but still don't work. I Don't see any plugin with the name you mention. See the pictures below :
![quantum1](https://user-images.githubusercontent.com/30263049/102685488-4d952880-41e1-11eb-9bbb-9b7b1a0c01b3.png)
![quantum2](https://user-images.githubusercontent.com/30263049/102685491-52f27300-41e1-11eb-9a11-1e3c18b8c115.png)
![quantum3](https://user-images.githubusercontent.com/30263049/102685521-9947d200-41e1-11eb-854b-c6f90871b2f6.png)
![quantum4](https://user-images.githubusercontent.com/30263049/102685523-9baa2c00-41e1-11eb-8b2b-c47e13367c1f.png)

Best
Philippe

**Comment by dmitriitux** [comment]
@pcombet-adosis not working in admin panel? or front-end?
