### ISSUE TITLE
Feature Requests as Media Replacement

### ISSUE THREAD

**Issue by philbertphotos** [Quantum-Manager/tracker#6]
Ability to open from Article Editor in back and front end
Ability to ad image or images to article via quantum manager
Ability to set permissions to certain folders.
Add a specific video and document folders.

**Comment by philbertphotos** [comment]
Let me install and test the new version and get back to you.

**Comment by philbertphotos** [comment]
Well while testing this message does not change. No errors in PHP no js errors
![image](https://user-images.githubusercontent.com/2892474/81324941-b15d4d80-9065-11ea-9736-0125ce9be07a.png)

**Comment by philbertphotos** [comment]
Found it ...guess its a bug
![image](https://user-images.githubusercontent.com/2892474/81325425-537d3580-9066-11ea-96a8-15f9c51c1394.png)

**Comment by dmitriitux** [comment]
@philbertphotos you need to install only the package, the component can only be installed on top, there is no check inside the component for other extensions

**Comment by dmitriitux** [comment]
http://polygon1.delo-design.ru/builds/qm/pkg_quantummanager.zip

**Comment by philbertphotos** [comment]
Thank you that works testing the new features now ...

**Comment by dmitriitux** [comment]
@philbertphotos here is changelog he is in Russian:
https://github.com/Quantum-Manager/quantummanager/blob/master/changelog.md

**Comment by dmitriitux** [comment]
@philbertphotos 
look at the plugin "Button - Embed Files (Quantum Manager)", I think you will like it
