### ISSUE TITLE
ETA of Front-End functionality

### ISSUE THREAD

**Issue by Babalion** [Quantum-Manager/tracker#62]
It would be really nice if one could use the Quantum Media Manager
for a much simpler and more modern upload process for **single article editing in front-end**!

As I have seen this feature is planned.
Can you already tell a estimated time of arrival?

**Comment by dmitriitux** [comment]
it is not yet clear. We can take it out even now, it's just a matter of safety.

**Comment by Babalion** [comment]
duplicate of https://github.com/Quantum-Manager/tracker/issues/3
