### ISSUE TITLE
Quantumtreecatalog and quantumbreadcrumbs missing and loading problem

### ISSUE THREAD

**Issue by ChristianW-ST** [Quantum-Manager/tracker#63]
First of all:
Joomla-Version: 3.9.24
PHP-Version: 7.3
Quantummanager: 1.7.0

My problem is:
the quantumtreecatalog and quantumbreadcrumbs ar not shown.

I tested several browsers, it's always the same.

The developer tools of the browser shows:
![problem](https://user-images.githubusercontent.com/22890244/107124150-567dae80-68a2-11eb-9fd3-825d568e7645.jpg)

Another problem is, that some folders are not loading (look the attachement).
![quant-prob2](https://user-images.githubusercontent.com/22890244/107229681-67532f00-6a1e-11eb-8953-889fb0cca04b.JPG)

I hope, that you can help me.

Greats,
Christian

**Comment by dmitriitux** [comment]
@ChristianW-ST can you send xhr a response to requests, what does it send? answers there ajax requests from the manager?

**Comment by ChristianW-ST** [comment]
@dmitriitux: sorry, i don't know, what you mean with "xhr response" and "ajax requests"

**Comment by dmitriitux** [comment]
> @dmitriitux: sorry, i don't know, what you mean with "xhr response" and "ajax requests"

ok, I'll record a video of what you need to do in chrome and throw it off

**Comment by b2z** [comment]
@ChristianW-ST https://developers.google.com/web/tools/chrome-devtools/network
You need Filter set to XHR https://developers.google.com/web/tools/chrome-devtools/network#filter
