### ISSUE TITLE
Не работает менеджер загрузки на php 8

### ISSUE THREAD

**Issue by bsakhanov** [Quantum-Manager/tracker#64]
Не работает менеджер загрузки на php 8
Попробовал перейти на php 8, обнаружил, что компонент начинает глючить. В частности, не отображает папки и файлы в своем интерфейсе.
Как воспроизвести?
Шаги для воспроизведения ошибки:
1. Просто откройте файловый менеджер из любого места (при выборе изображения для intro или full image в статье или сам компонент)
2. Смотрите ошибку

### Что хотелось бы?
**Чтобы компонент четко и безупречно работал бы на php 8**

Скриншот -- просто показывается гифка бесконечной загрузки и все. Больше ничего не появляется.
![v49](https://user-images.githubusercontent.com/45456925/107147446-623ba480-6978-11eb-9258-034e176032c8.jpg)

**Информация о системе (пожалуйста, заполните следующую информацию):**
  - Версия Расширения: 1.6.2

Тип базы данных | mysql
Версия базы данных | 5.5.5-10.4.12-MariaDB
Кодировка базы данных | utf8mb4_unicode_ci
Кодировка соединения базы данных | utf8mb4_general_ci
Версия PHP | 8.0.1
Веб-сервер | Apache
Интерфейс между веб-сервером и PHP | apache2handler
Версия Joomla! | Joomla! 3.9.24 Stable [ Amani ] 12-January-2021 15:00 GMT

**Comment by dmitriitux** [comment]
@bsakhanov ок,в следующей версии посмотрю и поправлю, я еще сам не переходил на php8

**Comment by dmitriitux** [comment]
работает на 8.1.4
