### ISSUE TITLE
How does permission override work with json format? Disable drag&drop area

### ISSUE THREAD

**Issue by djayko** [Quantum-Manager/tracker#65]
Hello,

I've a user group "Manager" and I want to adjust their rights and image paths by using override.

I set override to:

Role: Manager
config name: scopescustom
json: 

```
{
    "scopescustom0": {
        "enable": "1",
        "id": "generatefromtitle1",
        "title": "uploadareahidden",
        "dropareahidden": 1,
        "path":"/images/01-news/{year}/{month}/"
    }
}
```

This has no effect. Why?
What I am doing wrong?

What I want to achieve?
1. Drag & Drop upload area on new articles should be removed or 
2. only this area should use a predefined path for everyone  (it should differ to main quantum drag and drop field)

[Screenshot-LInk](https://i.ibb.co/fX7JCD0/2021-02-12-17-49-08-Beitr-ge-Bearbeiten-B-r-B-ren-baer-de-STIFTUNG-f-r-B-REN-FOUNDATION-for.png
)
best,
Ayko

**Comment by dmitriitux** [comment]
@djayko 
hi,
This is the field that predefines the media field from Joomla! does not take into profile the path configuration from the Quantum Manager

**Comment by dmitriitux** [comment]
It is only possible to change the general path for all these fields in the override plugin settings
