### ISSUE TITLE
BUG when insert image from Joomshaper SP Page Builder

### ISSUE THREAD

**Issue by toonetcreation** [Quantum-Manager/tracker#66]
**Describe the bug**
From SP page builder (front-end or back-end) when I want to replace an image inside an addon thanks to quantum manager does not work. Nothing appears after clicking INSERT button.
And, previpously, with version 1.6 was working, but the loading time was long.

**Expected behavior**
Image inserted correctly inside page builder addon.
Loading time correct/fast.

**Screenshots**
https://prnt.sc/zz8ws4

**System Information**
 - Extensions version 1.7.0
 - PHP version: 7.4.14
 - Server OS: Linux
 - Browser Chrome

**Additional context**

**Comment by dmitriitux** [comment]
ok, I'll fix it in the next release

**Comment by toonetcreation** [comment]
ok thanks

**Comment by dmitriitux** [comment]
@toonetcreation fix in verison 1.7.2

**Comment by toonetcreation** [comment]
Many thanks for the feedback
