### ISSUE TITLE
upload translation message

### ISSUE THREAD

**Issue by toonetcreation** [Quantum-Manager/tracker#69]
Hi,

Where is it possible to translate this message.
See attached file.

Thanks
L.

**Comment by dmitriitux** [comment]
@toonetcreation Hi, the attached file is not visible. Send again

**Comment by toonetcreation** [comment]
here it is : http://prntscr.com/10ke9xy

**Comment by dmitriitux** [comment]
@toonetcreation and, for sure, let's upload the latest files to the translation service. forgot

**Comment by dmitriitux** [comment]
service: https://www.transifex.com/norrnext/quantum-manager/

**Comment by toonetcreation** [comment]
ok thanks.
I have sent a request to join the team
