### ISSUE TITLE
Create a plg integration with EasySocial 4 

### ISSUE THREAD

**Issue by ssnobben** [Quantum-Manager/tracker#70]
Hi 

it would be nice if you could integrate with EasySocial 4 & Joomla 4

I think many should appreciate this though this combination would be very good.

**Comment by dmitriitux** [comment]
Hi, it doesn't take me long to adapt to joomla 4. I'll do it when it comes out in a few weeks. It's just that after the release, I myself will not actively use joomla 4.

As for easy social, I probably won't integrate. It's not worth it for the support, it's hard enough. I have experience of integration with yootheme pro and sp builder and it is difficult to maintain it in a free distribution format. And the creation of a paid integration will not solve much, the market is very small and for the sake of this I see no reason to bother, unfortunately.
