### ISSUE TITLE
thumbs not displayed with Balbooa Joomla Gallery

### ISSUE THREAD

**Issue by toonetcreation** [Quantum-Manager/tracker#71]
Hi,

I'm using Balbooa Joomla Gallery as gallery manager : https://www.balbooa.com/joomla-gallery
When I use Quantum Manager to browse images manages by Balbooa Joomla Gallery , thumbs are not displayed.
See here : https://prnt.sc/10ke9s3

How can I solve that?

Thanks
L.

**Comment by dmitriitux** [comment]
@toonetcreation can you see what is being sent there in the browser console? are there any mistakes

**Comment by toonetcreation** [comment]
here it is : http://prntscr.com/10m2vwt

**Comment by dmitriitux** [comment]
there is a duplication of the images/images folder. If you remove one image, will it open? as I understand it, the address is incorrectly generated for the cache of images

**Comment by toonetcreation** [comment]
I have solved the problem.
was coming from htaccess (generated by akeeba admin tools) to autorise reading quantum cache directory.
works fine now.
thank you

**Comment by b2z** [comment]
:+1:
