### ISSUE TITLE
Quantum Manager in frontend

### ISSUE THREAD

**Issue by galamarco** [Quantum-Manager/tracker#77]
**I need to allow a group of copywriters to use Quantum Manager in the frontend.**
It is a feature requested several times but I have not found the possibility to activate it.

Com_media is not  no longer beautiful or safer, but it is certainly more incomplete and uncomfortable

It would be very useful to **allow site administrators to choose to enable it based on user permissions** so as to take advantage of the valuable features it has Quantum Manager in frontend.

Best regards
Marco

**Comment by dmitriitux** [comment]
we understand what needs to be brought to the front. But we still cannot find a free security specialist. To work with him on this matter.

**Comment by Sulpher** [comment]
Front-end is done. 
See version 2.0.0.
