### ISSUE TITLE
Insert Button does not work in Acymailing

### ISSUE THREAD

**Issue by coolcat-creations** [Quantum-Manager/tracker#79]
**Describe the bug**
When you use the Manager in Acymailing the insert Button does not work. By clicking on it simply nothing happens.

**To Reproduce**
1. Go to a Joomla Installation with Acymailing (I use V. 7)
2. Create a new Newsletter,
3. Try to insert an image through Quantum

**Expected behavior**
The insert button should insert the image

**System Information (please complete the following information):**
 - Extensions version  1.7.3
 - PHP version: 7.3
 - Server OS: Linus
 - Browser Firefox

**Comment by dmitriitux** [comment]
I understand, I'll take a look, but I can't make friends between Acymailing and the manager =)

**Comment by dmitriitux** [comment]
haven't made support for this extension yet

**Comment by dmitriitux** [comment]
@coolcat-creations Will the free version of the extension be enough for me to start the insert?

**Comment by coolcat-creations** [comment]
Hi @dmitriitux yes absolutely

**Comment by Sulpher** [comment]
Integration with AcyMailing is done.

See the announcement: https://norrnext.com/blog/quantum-manager-3-1-0-released
