### ISSUE TITLE
Select button of quantum manager is closing both modals when field is part of a repeatable field

### ISSUE THREAD

**Issue by knowmatesSR** [Quantum-Manager/tracker#81]
**Describe the bug**
Select button of quantum manager is closing both modals when field is part of a repeatable field

**To Reproduce**
1. Create a repeatable field containign a media field
2. choose media 
3. click select
4. both modals (repeatable field modal and quantum modal are closed now) 

**Expected behavior**
Only  quantum manager modal should be closed now

**System Information (please complete the following information):**
 - Extensions version 1.4.1

**To fix it temporary:**
replace line 37 in file administrator/templates/[YOUR BACKEND TEMPLATE]/js/plg_system_quantummanagermedia/modalfield.js with this line `window.parent.jQuery('.modal.hide.in').last().modal('hide');`

**Comment by dmitriitux** [comment]
now the current version is 1.7.3. I may have already fixed that. Can you update the entire package?

**Comment by knowmatesSR** [comment]
Sorry, I've picked the version number from quantummanagermedia.xml. But the package version number is the latest one (1.7.3).

**Comment by dmitriitux** [comment]
@knowmatesSR ок.

**Comment by dmitriitux** [comment]
@knowmatesSR I'll check if the Quantum has its own JForm field, and you can use it. I recently created a universal plugin for fields, where you can create any JForm fields.
Universal field: https://github.com/Delo-Design/radicaluniversalfield
Lib fields: https://github.com/JPathRu/lib_fields
Field from Quantum: https://github.com/JPathRu/lib_fields/blob/master/docs/fields/quantumuploadimage.md

Lib_fields is a JForm field library that comes with the package. And there is a field for quantum. It can be loaded into custom material fields if you use a unversal field. The documentation is only in Russian so far. Not translated yet.

You can write to me in telegram, I will help set up.
Telegram https://t.me/tsymbalmitia

**Comment by dmitriitux** [comment]
About the error: I will check and correct

**Comment by dmitriitux** [comment]
https://github.com/Quantum-Manager/quantummanagermedia/commit/229e8afbd91fe68160b1cf9cfc5aabc65c29a1bf
