### ISSUE TITLE
Joomla 4 support?

### ISSUE THREAD

**Issue by crystalenka** [Quantum-Manager/tracker#85]
**Is your feature request related to a problem? Please describe.**
Quantum Manager does not currently support Joomla 4 (as far as I can see).

**Describe the solution you'd like**
I would love to be able to continue to use it as my clients start to move to Joomla 4!

**Describe alternatives you've considered**
Com_media 😭

**Additional context**
Joomla 4 is due to be released this month and some clients are anxious to switch.

**Comment by dmitriitux** [comment]
in fact almost everything is done, I removed the jquery code that was by writing a compatible api. I need to rewrite a few installer files there. And the longest thing is to look at the plugins, the logic of the media fields has changed a little. Plugins, that is, I need to adapt a little. I will do this before October. It's just that we still abruptly do not switch to joomla 4 ourselves, because our entire stack of extensions did not switch to joomla 4

**Comment by dmitriitux** [comment]
![photo_2021-08-04 11 48 21](https://user-images.githubusercontent.com/6643167/128151561-1235ed64-6b96-45c6-a2c9-10ec5d092e61.jpeg)
here is how it looks for now, but we still need to tweak a little css and js scripts. I don't want to have two different versions for different joomla. I try to combine everything in one.

**Comment by crystalenka** [comment]
That's fantastic news, I am glad you are working on it! Looks great, I can't wait to try. Is there a way I can install it on a test site, or is it not ready for an installation package? (When I tried to install the most recent stable version it gave me an error.)

Thank you! You're awesome.
Crystal

**Comment by dmitriitux** [comment]
you can download the master branch of the component, and delete the script.php file from the archive, then rebuild the archive from this. and then you can upload to joomla 4

**Comment by dmitriitux** [comment]
https://github.com/Quantum-Manager/quantummanager

**Comment by crystalenka** [comment]
Thank you!

**Comment by bsakhanov** [comment]
Добрый день, Дмитрий! Было бы конечно очень классно, если выпустите уже готовый релиз для joomla 4!

**Comment by dmitriitux** [comment]
> Добрый день, Дмитрий! Было бы конечно очень классно, если выпустите уже готовый релиз для joomla 4!

Я сейчас продумываю и буду переписывать архитектуру менеджера, потому что стали проблемы развития, нужно его архитектуру улучшить

**Comment by bsakhanov** [comment]
Спасибо за труды. Просто невероятно удобный и технологичный компонент! Ждем с нетерпением новой версии!

**Comment by Heart1010** [comment]
👍 I'm also thankful and waiting for the J4 version. Thanks @dmitriitux

**Comment by dmitriitux** [comment]
@Heart1010 I am rewriting the architecture of the manager, making it cross-platform now. We need to break it down and rewrite it.

**Comment by dmitriitux** [comment]
@Heart1010 @crystalenka
you can look at your testing grounds.
Now only the interception plugin and the insertion plugin from quantum do not work. The interception plugin is not enabled now after installation. And there an error with the installation of the lib_fields library is shown, you can ignore it.

[https://hika.su/builds/free/dev_pkg_quantummanager.zip](https://hika.su/builds/free/dev_pkg_quantummanager.zip)

Do not be afraid of the hika.su domain =)

**Comment by makswell1986** [comment]
Здравствуйте Дмитрий не работает импорт изображений в редакторе материалов в joomla 4.4.3 после обновления. Плагин сам работает открывается а вот тут его нет в изображении для вводного текста
![Снимок](https://github.com/Quantum-Manager/tracker/assets/103573411/e0c9c46c-c180-41ac-99bd-6129a0231a95)
Пожалуйста помогите с этим вопросом

**Comment by makswell1986** [comment]
> Здравствуйте Дмитрий не работает импорт изображений в редакторе материалов в joomla 4.4.3 после обновления. Плагин сам работает открывается а вот тут его нет в изображении для вводного текста ![Снимок](https://private-user-images.githubusercontent.com/103573411/312359563-e0c9c46c-c180-41ac-99bd-6129a0231a95.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTU3NzcsIm5iZiI6MTcxMDQxNTQ3NywicGF0aCI6Ii8xMDM1NzM0MTEvMzEyMzU5NTYzLWUwYzljNDZjLWMxODAtNDFhYy05OWJkLTYxMjlhMDIzMWE5NS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxMTI0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzAzZTcxMTg5OWIzYjNkZjQ3Y2Y5NjMzNDE5OTYwZGM1OWQ3NDhmYWE0ZTFiYjZlMTZjOGM4NTMwZjBhMGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UcmDuZNnCHaG8jYVKsF5jKw0dsPeEw5_1FEWd9CAifA) Пожалуйста помогите с этим вопросом

Решение найдено, необходимо удалить папку /media/lib_fields. Затем заново переустановить компонент

**Comment by Sulpher** [comment]
Quantum Manager supports both Joomla 4 / 5 now. I am closing the ticket. 
Thanks to everyone.
