### ISSUE TITLE
There seems to be a conflict between Quantum manager and Frontend protection in Akeeba admin tools.

### ISSUE THREAD

**Issue by bokkokana** [Quantum-Manager/tracker#89]
Hello,

Thank you for always making good products. I would like to ask you one question.

**Describe the bug**
It seems that when we enable frontend protection of the htaccess maker in Akeeba admin tools, we can't see the thumbnails in Quantum manager.

**To Reproduce**
When I enable frontend protection in the htaccess maker operation screen of Akeeba admin tools, the thumbnail of Quantum manager is broken as shown in the attached image. However, it is only the thumbnail that is broken, and if I click on it and select edit, I can see the edit screen for the image.

I was wondering if the exception function of the htaccess maker in Akeeba admin tools would work, so I contacted the support section of Admin tools and got the following response.

"First of all, you are not following the instructions correctly. It tells you to add the file which gets blocked, not the file which tries to load the blocked file, to the exceptions list. The files being blocked are joomla_black.png and powered_by.png.

The second thing I observer is that the URLs of the files are wrong. These files are in the images folder of your site. However, Quantum is trying to load them from your site's root where they do not exist. You should report this as a bug to Quantum, showing them the same first screenshot you sent us."

I don't know anything about coding, so I can't even judge whether what they are saying is correct or not.

Of course, I can disable frontend protection only when editing images and turn it back on when I'm done, but it's somewhat cumbersome and I'd be happy if this conflict could be resolved.

**Expected behavior**
I want to use Akeeba admin tools' frontend protection and Quantum manager at the same time.

**Screenshots**
https://prnt.sc/1rdkvjf
https://prnt.sc/1rdkxwz
https://prnt.sc/1rdkz02

**System Information (please complete the following information):**
 - Extensions version [both newest]
 - PHP version: [7.4]
 - Server OS: [Linux]
 - Browser [firefox]

**Additional context**
If anyone has any good advice, please let me know. Thank you very much.

Kana

<img width="1649" alt="quantummanager-with-frontend-protection" src="https://user-images.githubusercontent.com/90181543/132187939-6db383b4-2320-4ca9-93fa-4fff9f95053a.png">
<img width="868" alt="frontend-protection" src="https://user-images.githubusercontent.com/90181543/132187929-3a436a4b-ecd5-42a6-ad41-0369ef60acb6.png">
<img width="1650" alt="quantummanager-without-frontend-protection" src="https://user-images.githubusercontent.com/90181543/132187916-cf313887-3a3c-49dd-af2d-9dbdf90d8ece.png">

**Comment by dmitriitux** [comment]
First, I'll try to explain how sketches work.

All thumbnails refer to a php script that generates a generated thumbnail in the cache folder. This is done in order, for example, from webp or in the future video to generate a preview image. After successful generation, the script redirects to a physical address in the cache.

Here's how it works if the addresses are:

/administrator/index.php?option=com_quantummanager&task=quantumviewfiles.generatePreviewImage&scope=images&file=powered_by.png&path=root&v=562075

redirect -> 

 /cache/com_quantummanager/images/powered_by.png?v=743250

**Comment by dmitriitux** [comment]
as I understand it, you just need to allow the cache folder

**Comment by dmitriitux** [comment]
or folder: cache/com_quantummanager

**Comment by dmitriitux** [comment]
there the response code is 403, it is simply forbidden. you were described incorrectly that there are no files. everything is correct. it locks the cache folder so nothing is displayed

**Comment by dmitriitux** [comment]
There is nothing wrong with opening the cache folder from a security standpoint. There is usually some kind of static files (pictures for example). And all the php files that are generated from joomla and normal extensions there are registered checks from direct access to these files. We do not block this folder on our projects.

**Comment by bokkokana** [comment]
Super!
Both methods(cache/ and cache/com_quantummanager) work well.
I put "cache/com_quantummanager" to "Allow direct access, including .php files, to these directories" of htaccess maker, then thumbs appeared.

Thank you very much!
