### ISSUE TITLE
Cannot insert image in AcyMailing

### ISSUE THREAD

**Issue by renekreijveld** [Quantum-Manager/tracker#91]
When the plugin Redirect Media (com_media) call to Quantum Manager is published Quantum Manager is unusable in AcyMailing version 7.

**Describe the bug**
When the plugin Redirect Media (com_media) call to Quantum Manager is published Quantum Manager is unusable in AcyMailing version 7. When an image is selected it isn't inserted in the newsletter layout.

**To Reproduce**
1. Publish the Redirect Media (com_media) call to Quantum Manager plugin.
2. Create a new newsletter in Acy Mailing.
3. Insert en Image block into the newsletter.
4. Click on the Media Manager button to choose an image.
5. Quantum Manager is openend.
6. Choose an image and click on the Select button an the top of the Quantum Manager.
7. Nothing happens.

**Expected behavior**
At step 6, the image should be inserted into the newsletter layout.

**System Information (please complete the following information):**
 - Joomla: 3.10.2
 - Quantum Manager: 1.8.0
 - AcyMailing: 7.6.0
 - PHP version: 7.4.21
 - Browser: Google Chrome

**Comment by dmitriitux** [comment]
Hi, I know about this problem. Tried to integrate into this extension, had problems. Will try again to sit down and figure it out

**Comment by Sulpher** [comment]
Integration with AcyMailing is done.

See the announcement: https://norrnext.com/blog/quantum-manager-3-1-0-released
