### ISSUE TITLE
Not working with Acymailing Component

### ISSUE THREAD

**Issue by pnkr** [Quantum-Manager/tracker#92]
**Describe the bug**
I use Acymailing Component to create my marketing emails. When i try to insert an image to the email, quantum manager opens, i select the image i want and i hit the select button to insert the image but nothing happens.

**To Reproduce**
Go to Acymailing Extention, Hit the Email button, and on the top right hit the Create mail button. On the Email editor try to insert an image, select the image and hit insert.

**Expected behavior**
After you select the image and hit insert popup window should close and the image to appear in the editor.

**Screenshots**

**System Information (please complete the following information):**
 - Extensions version [e.g. 1.8.0]
 - PHP version: [e.g. 7.4]
 - Server OS: [e.g. Linux]
 - Browser firefox / chrome / edge

**Additional context**
Other media manager like JCE or the default joomla media manager work fine.

**Comment by pnkr** [comment]
sorry didnt saw that the issue was already mentioned.

**Comment by Sulpher** [comment]
Integration with AcyMailing done.

See the announcement: https://norrnext.com/blog/quantum-manager-3-1-0-released
