### ISSUE TITLE
PNG and JPG not visible see sceenshot

### ISSUE THREAD

**Issue by Lumiga** [Quantum-Manager/tracker#94]
PNG and JPG not visible see sceenshot.
We have tested this on two websites. We don't know how to fix this.
In other media managers (Joomla and JCE) we have no issues.
Only SVG are visible.

https://lumiga.nl/1/screenshot-154.jpg

**Comment by dmitriitux** [comment]
what web server? can you see the response from ajax requests from the server in the browser console?

**Comment by Lumiga** [comment]
We host all our website at https://combell.nl

When we reset .htaccess form Admin Tools too the default .htaccess file from Joomla the issue is solved.
So do you know which part of the htaccess maker form Admin Tools we have to turn off? 
Or which Exceptions we have to set to folders or files?

Maybe related to this issue?
https://www.akeeba.com/support/admin-tools/Ticket/35754:frontend-protection-of-htaccess-maker-seems-to-conflict-with-quantum-manager.html

"Can you see the response from ajax requests from the server in the browser console?"
How can I do that?

**Comment by dmitriitux** [comment]
the /cache folder must be allowed
all previews are generated in the cache folder

**Comment by Lumiga** [comment]
Thanks but the still we don't see images. It keeps loading.

We have this error, and if we delete the htacces file this error is gone:

 For further info see https://en.wikipedia.org/wiki/Self-XSS 
index.php:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.done (quantumviewfiles.js?1639474644:957)
    at XMLHttpRequest.ajax.request.onreadystatechange (utils.js?1639474644:114)
index.php:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.done (quantumtreecatalogs.js?1639474644:64)
    at XMLHttpRequest.ajax.request.onreadystatechange (utils.js?1639474644:114)

**Comment by dmitriitux** [comment]
But can you send the answer to the request itself in the "network" tab? There will simply be at least something to understand what is wrong

**Comment by Lumiga** [comment]
I found out the right configuration.

Basic security Reflected XSS prevention has to turn off.

Folder media/ has to Allow direct access, including .php files, to these directories

Folder cache/ has to Allow direct access, except .php files, to these directories

**Comment by dmitriitux** [comment]
@Lumiga problem solved?

**Comment by StuckNkode** [comment]
How/where do you find the settings for these:

Basic security Reflected XSS prevention has to turn off.

Folder media/ has to Allow direct access, including .php files, to these directories

Folder cache/ has to Allow direct access, except .php files, to these directories

Thanks... sorry, I'm just a semi-technical guy who doesn't run into this sort of thing often... any help will be much appreciated.

**Comment by dmitriitux** [comment]
@StuckNkode 
are you asking something? I just don't see

**Comment by StuckNkode** [comment]
I just responded to a poll on the quality of the response Dimitri… which was, excellent by the way. I’ve already bought, installed, and am using the plugin. Excellent product.
Thanks,

**Comment by dmitriitux** [comment]
@StuckNkode understood
