### ISSUE TITLE
Add Media to System - Quantum Manager integration with YOOtheme Pro

### ISSUE THREAD

**Issue by Lumiga** [Quantum-Manager/tracker#95]
Hi,

It's great that Quantum Manager is integrated to Yootheme Pro.
But I found one place where the Quantum Manager not yet is integrated.

See screenshot: https://lumiga.nl/1/screenshot-155.jpg

Kind regards,
Lumiga

**Comment by dmitriitux** [comment]
it's hard for me to integrate there. There are not many APIs for their vue program. I just did the integration with ordinary fields outside of vue, intercepting uikit events and the usual DOM. But there is no crawling in there yet.
