### ISSUE TITLE
Joomla 4

### ISSUE THREAD

**Issue by lakerdoc** [Quantum-Manager/tracker#96]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lakerdoc** [comment]
Hi
I loved to use the Quantum Manager, but unfortunately there is no support for Joomla 4
Do you have any plans therefore?
thx

**Comment by dmitriitux** [comment]
@lakerdoc 
yes, there will be support for joomla 4. I'm just now rewriting the entire file manager from scratch, which will open up the potential of the file manager on the site much wider.

But joomla 4 has a new file manager, could you tell us why quantum is preferable to you than the built-in file manager in joomla 4?

**Comment by dmitriitux** [comment]
the next release will be with adaptation for joomla 4
