### ISSUE TITLE
can I uninstall Lib fields ?

### ISSUE THREAD

**Issue by toonetcreation** [Quantum-Manager/tracker#97]
Hi,

If I do not use quantum manager anymore, can I uninstall Lib fields https://prnt.sc/26mtecy ?

Thanks
L.

**Comment by dmitriitux** [comment]
@toonetcreation 
In extension management. Highlight lib_fields and delete.
Why can't you use it anymore? Because they switched to joomla 4?

**Comment by toonetcreation** [comment]
ok I will do this.
just for info, lib_fields is only linked/used by quantum manager ?
for the moment I cannot use quantum manager due to 3 things :
- joomla 4 compatibility
- php8 compatibility
- front-end accessibility (from meu item to allow user/manager to browser pictures, files etc...directly from the website front-end)

except these points, quantum manager component is perfect :-)

**Comment by dmitriitux** [comment]
> just for info, lib_fields is only linked/used by quantum manager ?

most likely on your site

we will add front-loading in the next version, which will be released soon. Php 8 I’ll see where it falls, we just haven’t made the transition to it ourselves, there are a lot of nuances. As for Joomla 4, a new version is being written from scratch. And it will eclipse everything that was before =)

**Comment by toonetcreation** [comment]
ok so wonderful ;-)
